//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 12:50:28 PM CET 
//


package eu.fittest.common.core.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.fittest.common.core.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.fittest.common.core.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegisterAgent }
     * 
     */
    public RegisterAgent createRegisterAgent() {
        return new RegisterAgent();
    }

    /**
     * Create an instance of {@link RequestProperties }
     * 
     */
    public RequestProperties createRequestProperties() {
        return new RequestProperties();
    }

    /**
     * Create an instance of {@link DeployComponent }
     * 
     */
    public DeployComponent createDeployComponent() {
        return new DeployComponent();
    }

    /**
     * Create an instance of {@link Delete }
     * 
     */
    public Delete createDelete() {
        return new Delete();
    }

    /**
     * Create an instance of {@link ExecuteResponse }
     * 
     */
    public ExecuteResponse createExecuteResponse() {
        return new ExecuteResponse();
    }

    /**
     * Create an instance of {@link Upload }
     * 
     */
    public Upload createUpload() {
        return new Upload();
    }

    /**
     * Create an instance of {@link ResourceAvailable }
     * 
     */
    public ResourceAvailable createResourceAvailable() {
        return new ResourceAvailable();
    }

    /**
     * Create an instance of {@link Start }
     * 
     */
    public Start createStart() {
        return new Start();
    }

    /**
     * Create an instance of {@link PolicyFileRequest }
     * 
     */
    public PolicyFileRequest createPolicyFileRequest() {
        return new PolicyFileRequest();
    }

    /**
     * Create an instance of {@link RegisteredComponents }
     * 
     */
    public RegisteredComponents createRegisteredComponents() {
        return new RegisteredComponents();
    }

    /**
     * Create an instance of {@link Execute }
     * 
     */
    public Execute createExecute() {
        return new Execute();
    }

    /**
     * Create an instance of {@link RequestProperties.Property }
     * 
     */
    public RequestProperties.Property createRequestPropertiesProperty() {
        return new RequestProperties.Property();
    }

    /**
     * Create an instance of {@link PropertiesResponse.Property }
     * 
     */
    public PropertiesResponse.Property createPropertiesResponseProperty() {
        return new PropertiesResponse.Property();
    }

    /**
     * Create an instance of {@link UploadResource }
     * 
     */
    public UploadResource createUploadResource() {
        return new UploadResource();
    }

    /**
     * Create an instance of {@link Stop }
     * 
     */
    public Stop createStop() {
        return new Stop();
    }

    /**
     * Create an instance of {@link StartSerializationResponse }
     * 
     */
    public StartSerializationResponse createStartSerializationResponse() {
        return new StartSerializationResponse();
    }

    /**
     * Create an instance of {@link PropertiesResponse }
     * 
     */
    public PropertiesResponse createPropertiesResponse() {
        return new PropertiesResponse();
    }

    /**
     * Create an instance of {@link Register }
     * 
     */
    public Register createRegister() {
        return new Register();
    }

    /**
     * Create an instance of {@link CrossDomainPolicy }
     * 
     */
    public CrossDomainPolicy createCrossDomainPolicy() {
        return new CrossDomainPolicy();
    }

    /**
     * Create an instance of {@link CrossDomainPolicy.AllowAccessFrom }
     * 
     */
    public CrossDomainPolicy.AllowAccessFrom createCrossDomainPolicyAllowAccessFrom() {
        return new CrossDomainPolicy.AllowAccessFrom();
    }

    /**
     * Create an instance of {@link KeepAlive }
     * 
     */
    public KeepAlive createKeepAlive() {
        return new KeepAlive();
    }

    /**
     * Create an instance of {@link Initialize.Parameter }
     * 
     */
    public Initialize.Parameter createInitializeParameter() {
        return new Initialize.Parameter();
    }

    /**
     * Create an instance of {@link ExecutedTestCase }
     * 
     */
    public ExecutedTestCase createExecutedTestCase() {
        return new ExecutedTestCase();
    }

    /**
     * Create an instance of {@link Kill }
     * 
     */
    public Kill createKill() {
        return new Kill();
    }

    /**
     * Create an instance of {@link Download }
     * 
     */
    public Download createDownload() {
        return new Download();
    }

    /**
     * Create an instance of {@link Terminate }
     * 
     */
    public Terminate createTerminate() {
        return new Terminate();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link RegisterResponse }
     * 
     */
    public RegisterResponse createRegisterResponse() {
        return new RegisterResponse();
    }

    /**
     * Create an instance of {@link RegisterComponent }
     * 
     */
    public RegisterComponent createRegisterComponent() {
        return new RegisterComponent();
    }

    /**
     * Create an instance of {@link Deregister }
     * 
     */
    public Deregister createDeregister() {
        return new Deregister();
    }

    /**
     * Create an instance of {@link UserDialog }
     * 
     */
    public UserDialog createUserDialog() {
        return new UserDialog();
    }

    /**
     * Create an instance of {@link RegisterAgentReponse }
     * 
     */
    public RegisterAgentReponse createRegisterAgentReponse() {
        return new RegisterAgentReponse();
    }

    /**
     * Create an instance of {@link StopSerialization }
     * 
     */
    public StopSerialization createStopSerialization() {
        return new StopSerialization();
    }

    /**
     * Create an instance of {@link Progress }
     * 
     */
    public Progress createProgress() {
        return new Progress();
    }

    /**
     * Create an instance of {@link Initialize }
     * 
     */
    public Initialize createInitialize() {
        return new Initialize();
    }

    /**
     * Create an instance of {@link StartSerialization }
     * 
     */
    public StartSerialization createStartSerialization() {
        return new StartSerialization();
    }

}
