/*
 * This file was automatically generated by EvoSuite
 */

package eu.fittest.efsm2ct.sut;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.fittest.efsm2ct.sut.TestFlexstore;
import eu.fittest.fbk.efsm2ct.efsm2mon.runtime.FsmtesterException;
import eu.fittest.fbk.efsm2ct.efsm2mon.runtime.NotApplicableException;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;

public class TestTestFlexstore {

  //Test case number: 0
  /*
   * 26 covered goals:
   * 1 eu.fittest.efsm2ct.sut.TestFlexstore.removeButton66_click()V: I9 Branch 23 IF_ICMPEQ L275 - true
   * 2 eu.fittest.efsm2ct.sut.TestFlexstore.removeButton66_click()V: I21 Branch 24 IFNE L278 - true
   * 3 eu.fittest.efsm2ct.sut.TestFlexstore.removeButton66_click()V: I146 Branch 25 LOOKUPSWITCH L314 Case 2 - true
   * 4 eu.fittest.efsm2ct.sut.TestFlexstore.removeButton66_click()V: I146 Branch 26 LOOKUPSWITCH L314 Default-Case - false
   * 5 eu.fittest.efsm2ct.sut.TestFlexstore.removeButton66_click()V: I150 Branch 27 IFNE L317 - false
   * 6 eu.fittest.efsm2ct.sut.TestFlexstore.removeButton66_click()V: I152 Branch 28 IFNE L317 - false
   * 7 eu.fittest.efsm2ct.sut.TestFlexstore.removeButton66_click()V: I154 Branch 29 IFLE L317 - false
   * 8 eu.fittest.efsm2ct.sut.TestFlexstore._shutdown()V: I8 Branch 3 IFNE L75 - false
   * 9 eu.fittest.efsm2ct.sut.TestFlexstore.purchase21_click()V: I9 Branch 4 IF_ICMPEQ L97 - true
   * 10 eu.fittest.efsm2ct.sut.TestFlexstore.purchase21_click()V: I21 Branch 5 IFNE L100 - true
   * 11 eu.fittest.efsm2ct.sut.TestFlexstore.purchase21_click()V: I146 Branch 6 LOOKUPSWITCH L136 Case 1 - true
   * 12 eu.fittest.efsm2ct.sut.TestFlexstore.purchase21_click()V: I146 Branch 7 LOOKUPSWITCH L136 Default-Case - false
   * 13 eu.fittest.efsm2ct.sut.TestFlexstore.purchase21_click()V: I150 Branch 8 IFLE L139 - false
   * 14 eu.fittest.efsm2ct.sut.TestFlexstore.purchase21_click()V: I152 Branch 9 IFNE L139 - false
   * 15 eu.fittest.efsm2ct.sut.TestFlexstore.purchase21_click()V: I154 Branch 10 IFLE L139 - false
   * 16 eu.fittest.efsm2ct.sut.TestFlexstore.ButtonBar0_itemclick(I)V: I18 Branch 11 IF_ICMPEQ L175 - false
   * 17 eu.fittest.efsm2ct.sut.TestFlexstore.ButtonBar0_itemclick(I)V: I20 Branch 12 IFEQ L175 - true
   * 18 eu.fittest.efsm2ct.sut.TestFlexstore.ButtonBar0_itemclick(I)V: I32 Branch 13 IFNE L179 - true
   * 19 eu.fittest.efsm2ct.sut.TestFlexstore.ButtonBar0_itemclick(I)V: I158 Branch 14 LOOKUPSWITCH L215 Case 0 - true
   * 20 eu.fittest.efsm2ct.sut.TestFlexstore.ButtonBar0_itemclick(I)V: I158 Branch 15 LOOKUPSWITCH L215 Case 1 - false
   * 21 eu.fittest.efsm2ct.sut.TestFlexstore.ButtonBar0_itemclick(I)V: I158 Branch 16 LOOKUPSWITCH L215 Default-Case - false
   * 22 eu.fittest.efsm2ct.sut.TestFlexstore.ButtonBar0_itemclick(I)V: I227 Branch 20 IFNE L240 - false
   * 23 eu.fittest.efsm2ct.sut.TestFlexstore.ButtonBar0_itemclick(I)V: I229 Branch 21 IFNE L240 - false
   * 24 eu.fittest.efsm2ct.sut.TestFlexstore.ButtonBar0_itemclick(I)V: I231 Branch 22 IFLE L240 - false
   * 25 eu.fittest.efsm2ct.sut.TestFlexstore._startup()V: I8 Branch 1 IFNONNULL L35 - true
   * 26 eu.fittest.efsm2ct.sut.TestFlexstore._startup()V: I22 Branch 2 IFNE L41 - true
   */  @Test
  public void test0()  throws Throwable  {
      int int0 = 0;
      TestFlexstore.ButtonBar0_itemclick(int0);
      TestFlexstore.purchase21_click();
      TestFlexstore.removeButton66_click();
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 eu.fittest.efsm2ct.sut.TestFlexstore.purchase21_click()V: I9 Branch 4 IF_ICMPEQ L97 - false
   * 2 eu.fittest.efsm2ct.sut.TestFlexstore.purchase21_click()V: I21 Branch 5 IFNE L100 - false
   */  @Test
  public void test1()  throws Throwable  {
      int int0 = 0;
      TestFlexstore.ButtonBar0_itemclick(int0);
      try {
        TestFlexstore.purchase21_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * purchase21_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 2
  /*
   * 6 covered goals:
   * 1 eu.fittest.efsm2ct.sut.TestFlexstore.ButtonBar0_itemclick(I)V: I18 Branch 11 IF_ICMPEQ L175 - true
   * 2 eu.fittest.efsm2ct.sut.TestFlexstore.ButtonBar0_itemclick(I)V: I158 Branch 14 LOOKUPSWITCH L215 Case 0 - false
   * 3 eu.fittest.efsm2ct.sut.TestFlexstore.ButtonBar0_itemclick(I)V: I158 Branch 15 LOOKUPSWITCH L215 Case 1 - true
   * 4 eu.fittest.efsm2ct.sut.TestFlexstore.ButtonBar0_itemclick(I)V: I162 Branch 17 IFNE L219 - false
   * 5 eu.fittest.efsm2ct.sut.TestFlexstore.ButtonBar0_itemclick(I)V: I164 Branch 18 IFNE L219 - false
   * 6 eu.fittest.efsm2ct.sut.TestFlexstore.ButtonBar0_itemclick(I)V: I166 Branch 19 IFLE L219 - false
   */  @Test
  public void test2()  throws Throwable  {
      int int0 = 0;
      TestFlexstore.ButtonBar0_itemclick(int0);
      TestFlexstore.ButtonBar0_itemclick(int0);
  }

  //Test case number: 3
  /*
   * 2 covered goals:
   * 1 eu.fittest.efsm2ct.sut.TestFlexstore.removeButton66_click()V: I9 Branch 23 IF_ICMPEQ L275 - false
   * 2 eu.fittest.efsm2ct.sut.TestFlexstore.removeButton66_click()V: I21 Branch 24 IFNE L278 - false
   */  @Test
  public void test3()  throws Throwable  {
      try {
        TestFlexstore.removeButton66_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * removeButton66_click doesn't apply to current state:n1
         */
      }
  }
}
