/*
 * This file was automatically generated by EvoSuite
 */

package v2;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.fittest.fbk.efsm2ct.efsm2mon.runtime.FsmtesterException;
import eu.fittest.fbk.efsm2ct.efsm2mon.runtime.NotApplicableException;
import eu.fittest.fbk.efsm2ct.efsm2mon.runtime.SutCommunicationException;
import eu.fittest.fbk.efsm2ct.efsm2mon.runtime.UnderSpecifiedException;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import v2.TestFlex;

public class TestTestFlex {

  //Test case number: 0
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.Image2_click()V: I9 Branch 4 IF_ICMPNE L103 - true
   * 2 v2.TestFlex.Image2_click()V: I20 Branch 5 IFNE L106 - false
   * 3 v2.TestFlex._shutdown()V: I8 Branch 3 IFNE L80 - false
   * 4 v2.TestFlex._startup()V: I8 Branch 1 IFNONNULL L42 - true
   * 5 v2.TestFlex._startup()V: I22 Branch 2 IFNE L48 - true
   */  @Test
  public void test0()  throws Throwable  {
      try {
        TestFlex.Image2_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * Image2_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 1
  /*
   * 13 covered goals:
   * 1 v2.TestFlex.Image2_click()V: I9 Branch 4 IF_ICMPNE L103 - false
   * 2 v2.TestFlex.Image2_click()V: I20 Branch 5 IFNE L106 - true
   * 3 v2.TestFlex.Image2_click()V: I135 Branch 6 TABLESWITCH L138 Case 2 - true
   * 4 v2.TestFlex.Image2_click()V: I135 Branch 7 TABLESWITCH L138 Default-Case - false
   * 5 v2.TestFlex.Image2_click()V: I139 Branch 8 IFNE L176 - false
   * 6 v2.TestFlex.IDY_searchproduct_click()V: I9 Branch 368 IF_ICMPEQ L7711 - false
   * 7 v2.TestFlex.IDY_searchproduct_click()V: I13 Branch 369 IFEQ L7712 - true
   * 8 v2.TestFlex.IDY_searchproduct_click()V: I26 Branch 370 IFNE L7715 - true
   * 9 v2.TestFlex.IDY_searchproduct_click()V: I141 Branch 371 TABLESWITCH L7747 Case 0 - true
   * 10 v2.TestFlex.IDY_searchproduct_click()V: I141 Branch 372 TABLESWITCH L7747 Case 1 - false
   * 11 v2.TestFlex.IDY_searchproduct_click()V: I141 Branch 373 TABLESWITCH L7747 Case 2 - false
   * 12 v2.TestFlex.IDY_searchproduct_click()V: I141 Branch 374 TABLESWITCH L7747 Default-Case - false
   * 13 v2.TestFlex.IDY_searchproduct_click()V: I205 Branch 376 IFNE L7808 - false
   */  @Test
  public void test1()  throws Throwable  {
      TestFlex.IDY_searchproduct_click();
      TestFlex.Image2_click();
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_cancas_13_click()V: I9 Branch 9 IF_ICMPNE L211 - true
   * 2 v2.TestFlex.IDY_cancas_13_click()V: I20 Branch 10 IFNE L214 - false
   */  @Test
  public void test2()  throws Throwable  {
      try {
        TestFlex.IDY_cancas_13_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_cancas_13_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 3
  /*
   * 19 covered goals:
   * 1 v2.TestFlex.IDY_cancas_13_click()V: I9 Branch 9 IF_ICMPNE L211 - false
   * 2 v2.TestFlex.IDY_cancas_13_click()V: I20 Branch 10 IFNE L214 - true
   * 3 v2.TestFlex.IDY_cancas_13_click()V: I135 Branch 11 TABLESWITCH L246 Case 1 - true
   * 4 v2.TestFlex.IDY_cancas_13_click()V: I135 Branch 12 TABLESWITCH L246 Default-Case - false
   * 5 v2.TestFlex.IDY_cancas_13_click()V: I139 Branch 13 IFLE L285 - false
   * 6 v2.TestFlex.IDY_purchase_1_click()V: I9 Branch 250 IF_ICMPEQ L5229 - true
   * 7 v2.TestFlex.IDY_purchase_1_click()V: I27 Branch 252 IFNE L5233 - true
   * 8 v2.TestFlex.IDY_purchase_1_click()V: I142 Branch 253 TABLESWITCH L5265 Case 1 - false
   * 9 v2.TestFlex.IDY_purchase_1_click()V: I142 Branch 254 TABLESWITCH L5265 Case 2 - true
   * 10 v2.TestFlex.IDY_purchase_1_click()V: I142 Branch 255 TABLESWITCH L5265 Default-Case - false
   * 11 v2.TestFlex.IDY_purchase_1_click()V: I146 Branch 256 IFLE L5290 - false
   * 12 v2.TestFlex.ButtonBar0_itemclick(I)V: I17 Branch 294 IF_ICMPEQ L6161 - false
   * 13 v2.TestFlex.ButtonBar0_itemclick(I)V: I21 Branch 295 IFEQ L6162 - true
   * 14 v2.TestFlex.ButtonBar0_itemclick(I)V: I39 Branch 297 IFNE L6166 - true
   * 15 v2.TestFlex.ButtonBar0_itemclick(I)V: I155 Branch 298 TABLESWITCH L6198 Case 0 - true
   * 16 v2.TestFlex.ButtonBar0_itemclick(I)V: I155 Branch 299 TABLESWITCH L6198 Case 1 - false
   * 17 v2.TestFlex.ButtonBar0_itemclick(I)V: I155 Branch 300 TABLESWITCH L6198 Case 2 - false
   * 18 v2.TestFlex.ButtonBar0_itemclick(I)V: I155 Branch 301 TABLESWITCH L6198 Default-Case - false
   * 19 v2.TestFlex.ButtonBar0_itemclick(I)V: I219 Branch 303 IFNE L6258 - false
   */  @Test
  public void test3()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_cancas_13_click();
  }

  //Test case number: 4
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_purchase_3_click()V: I9 Branch 14 IF_ICMPNE L320 - true
   * 2 v2.TestFlex.IDY_purchase_3_click()V: I20 Branch 15 IFNE L323 - false
   */  @Test
  public void test4()  throws Throwable  {
      try {
        TestFlex.IDY_purchase_3_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_purchase_3_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 5
  /*
   * 16 covered goals:
   * 1 v2.TestFlex.IDY_purchase_3_click()V: I9 Branch 14 IF_ICMPNE L320 - false
   * 2 v2.TestFlex.IDY_purchase_3_click()V: I20 Branch 15 IFNE L323 - true
   * 3 v2.TestFlex.IDY_purchase_3_click()V: I135 Branch 16 TABLESWITCH L355 Case 1 - true
   * 4 v2.TestFlex.IDY_purchase_3_click()V: I135 Branch 17 TABLESWITCH L355 Default-Case - false
   * 5 v2.TestFlex.IDY_purchase_3_click()V: I139 Branch 18 IFLE L372 - false
   * 6 v2.TestFlex.IDY_cancas_4_click()V: I9 Branch 145 IF_ICMPEQ L3145 - true
   * 7 v2.TestFlex.IDY_cancas_4_click()V: I27 Branch 147 IFNE L3149 - true
   * 8 v2.TestFlex.IDY_cancas_4_click()V: I142 Branch 148 TABLESWITCH L3181 Case 1 - false
   * 9 v2.TestFlex.IDY_cancas_4_click()V: I142 Branch 149 TABLESWITCH L3181 Case 2 - true
   * 10 v2.TestFlex.IDY_cancas_4_click()V: I142 Branch 150 TABLESWITCH L3181 Default-Case - false
   * 11 v2.TestFlex.IDY_cancas_4_click()V: I146 Branch 151 IFNE L3208 - false
   * 12 v2.TestFlex.IDY_purchase_this_click()V: I9 Branch 284 IF_ICMPNE L5944 - false
   * 13 v2.TestFlex.IDY_purchase_this_click()V: I20 Branch 285 IFNE L5947 - true
   * 14 v2.TestFlex.IDY_purchase_this_click()V: I135 Branch 286 TABLESWITCH L5979 Case 2 - true
   * 15 v2.TestFlex.IDY_purchase_this_click()V: I135 Branch 287 TABLESWITCH L5979 Default-Case - false
   * 16 v2.TestFlex.IDY_purchase_this_click()V: I139 Branch 288 IFLE L6002 - false
   */  @Test
  public void test5()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_cancas_4_click();
      TestFlex.IDY_purchase_this_click();
      TestFlex.IDY_purchase_3_click();
  }

  //Test case number: 6
  /*
   * 3 covered goals:
   * 1 v2.TestFlex.IDY_addressState_close()V: I9 Branch 19 IF_ICMPEQ L429 - false
   * 2 v2.TestFlex.IDY_addressState_close()V: I14 Branch 20 IF_ICMPEQ L430 - false
   * 3 v2.TestFlex.IDY_addressState_close()V: I27 Branch 21 IFNE L433 - false
   */  @Test
  public void test6()  throws Throwable  {
      try {
        TestFlex.IDY_addressState_close();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_addressState_close doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 7
  /*
   * 7 covered goals:
   * 1 v2.TestFlex.IDY_addressState_close()V: I14 Branch 20 IF_ICMPEQ L430 - true
   * 2 v2.TestFlex.IDY_addressState_close()V: I27 Branch 21 IFNE L433 - true
   * 3 v2.TestFlex.IDY_labelPrice_15_click()V: I9 Branch 168 IF_ICMPNE L3637 - false
   * 4 v2.TestFlex.IDY_labelPrice_15_click()V: I20 Branch 169 IFNE L3640 - true
   * 5 v2.TestFlex.IDY_labelPrice_15_click()V: I135 Branch 170 TABLESWITCH L3672 Case 2 - true
   * 6 v2.TestFlex.IDY_labelPrice_15_click()V: I135 Branch 171 TABLESWITCH L3672 Default-Case - false
   * 7 v2.TestFlex.IDY_labelPrice_15_click()V: I139 Branch 172 IFNE L3712 - false
   */  @Test
  public void test7()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_labelPrice_15_click();
      TestFlex.IDY_purchase_this_click();
      try {
        TestFlex.IDY_addressState_close();
        fail("Expecting exception: SutCommunicationException");
      } catch(SutCommunicationException e) {
        /*
         * java.lang.RuntimeException: button not visible
         */
      }
  }

  //Test case number: 8
  /*
   * 7 covered goals:
   * 1 v2.TestFlex.IDY_purchase_7_click()V: I9 Branch 27 IF_ICMPNE L595 - true
   * 2 v2.TestFlex.IDY_purchase_7_click()V: I20 Branch 28 IFNE L598 - false
   * 3 v2.TestFlex.IDY_remove_shoppingCart_1_click()V: I9 Branch 289 IF_ICMPNE L6052 - false
   * 4 v2.TestFlex.IDY_remove_shoppingCart_1_click()V: I20 Branch 290 IFNE L6055 - true
   * 5 v2.TestFlex.IDY_remove_shoppingCart_1_click()V: I135 Branch 291 TABLESWITCH L6087 Case 1 - true
   * 6 v2.TestFlex.IDY_remove_shoppingCart_1_click()V: I135 Branch 292 TABLESWITCH L6087 Default-Case - false
   * 7 v2.TestFlex.IDY_remove_shoppingCart_1_click()V: I139 Branch 293 IFNE L6122 - false
   */  @Test
  public void test8()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_remove_shoppingCart_1_click();
      try {
        TestFlex.IDY_purchase_7_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_purchase_7_click doesn't apply to current state:n2
         */
      }
  }

  //Test case number: 9
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_purchase_7_click()V: I9 Branch 27 IF_ICMPNE L595 - false
   * 2 v2.TestFlex.IDY_purchase_7_click()V: I20 Branch 28 IFNE L598 - true
   * 3 v2.TestFlex.IDY_purchase_7_click()V: I135 Branch 29 TABLESWITCH L630 Case 1 - true
   * 4 v2.TestFlex.IDY_purchase_7_click()V: I135 Branch 30 TABLESWITCH L630 Default-Case - false
   * 5 v2.TestFlex.IDY_purchase_7_click()V: I139 Branch 31 IFLE L634 - false
   */  @Test
  public void test9()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_cancas_4_click();
      TestFlex.IDY_purchase_this_click();
      TestFlex.IDY_purchase_7_click();
  }

  //Test case number: 10
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_img_12_click()V: I9 Branch 32 IF_ICMPNE L704 - true
   * 2 v2.TestFlex.IDY_img_12_click()V: I20 Branch 33 IFNE L707 - false
   */  @Test
  public void test10()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      try {
        TestFlex.IDY_img_12_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_img_12_click doesn't apply to current state:n4
         */
      }
  }

  //Test case number: 11
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_img_12_click()V: I9 Branch 32 IF_ICMPNE L704 - false
   * 2 v2.TestFlex.IDY_img_12_click()V: I20 Branch 33 IFNE L707 - true
   * 3 v2.TestFlex.IDY_img_12_click()V: I135 Branch 34 TABLESWITCH L739 Case 2 - true
   * 4 v2.TestFlex.IDY_img_12_click()V: I135 Branch 35 TABLESWITCH L739 Default-Case - false
   * 5 v2.TestFlex.IDY_img_12_click()V: I139 Branch 36 IFNE L770 - false
   */  @Test
  public void test11()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_img_12_click();
  }

  //Test case number: 12
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_remove_shoppingCart_2_click()V: I9 Branch 37 IF_ICMPNE L812 - true
   * 2 v2.TestFlex.IDY_remove_shoppingCart_2_click()V: I20 Branch 38 IFNE L815 - false
   */  @Test
  public void test12()  throws Throwable  {
      try {
        TestFlex.IDY_remove_shoppingCart_2_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_remove_shoppingCart_2_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 13
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_remove_shoppingCart_2_click()V: I9 Branch 37 IF_ICMPNE L812 - false
   * 2 v2.TestFlex.IDY_remove_shoppingCart_2_click()V: I20 Branch 38 IFNE L815 - true
   */  @Test
  public void test13()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      try {
        TestFlex.IDY_remove_shoppingCart_2_click();
        fail("Expecting exception: SutCommunicationException");
      } catch(SutCommunicationException e) {
        /*
         * java.lang.RuntimeException: removeCartButton can't be invoked
         */
      }
  }

  //Test case number: 14
  /*
   * 8 covered goals:
   * 1 v2.TestFlex.IDY_remove_shoppingCart_2_click()V: I135 Branch 39 TABLESWITCH L847 Case 1 - true
   * 2 v2.TestFlex.IDY_remove_shoppingCart_2_click()V: I135 Branch 40 TABLESWITCH L847 Default-Case - false
   * 3 v2.TestFlex.IDY_remove_shoppingCart_2_click()V: I139 Branch 41 IFLE L878 - false
   * 4 v2.TestFlex.IDY_purchase_2_click()V: I9 Branch 363 IF_ICMPNE L7602 - false
   * 5 v2.TestFlex.IDY_purchase_2_click()V: I20 Branch 364 IFNE L7605 - true
   * 6 v2.TestFlex.IDY_purchase_2_click()V: I135 Branch 365 TABLESWITCH L7637 Case 1 - true
   * 7 v2.TestFlex.IDY_purchase_2_click()V: I135 Branch 366 TABLESWITCH L7637 Default-Case - false
   * 8 v2.TestFlex.IDY_purchase_2_click()V: I139 Branch 367 IFLE L7652 - false
   */  @Test
  public void test14()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_purchase_2_click();
      TestFlex.IDY_remove_shoppingCart_2_click();
  }

  //Test case number: 15
  /*
   * 7 covered goals:
   * 1 v2.TestFlex.Image3_click()V: I9 Branch 42 IF_ICMPNE L921 - true
   * 2 v2.TestFlex.Image3_click()V: I20 Branch 43 IFNE L924 - false
   * 3 v2.TestFlex.IDY_purchase_6_click()V: I9 Branch 95 IF_ICMPNE L2061 - false
   * 4 v2.TestFlex.IDY_purchase_6_click()V: I20 Branch 96 IFNE L2064 - true
   * 5 v2.TestFlex.IDY_purchase_6_click()V: I135 Branch 97 TABLESWITCH L2096 Case 2 - true
   * 6 v2.TestFlex.IDY_purchase_6_click()V: I135 Branch 98 TABLESWITCH L2096 Default-Case - false
   * 7 v2.TestFlex.IDY_purchase_6_click()V: I139 Branch 99 IFLE L2117 - false
   */  @Test
  public void test15()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_6_click();
      try {
        TestFlex.Image3_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * Image3_click doesn't apply to current state:n4
         */
      }
  }

  //Test case number: 16
  /*
   * 13 covered goals:
   * 1 v2.TestFlex.Image3_click()V: I9 Branch 42 IF_ICMPNE L921 - false
   * 2 v2.TestFlex.Image3_click()V: I20 Branch 43 IFNE L924 - true
   * 3 v2.TestFlex.Image3_click()V: I135 Branch 44 TABLESWITCH L956 Case 2 - true
   * 4 v2.TestFlex.Image3_click()V: I135 Branch 45 TABLESWITCH L956 Default-Case - false
   * 5 v2.TestFlex.Image3_click()V: I139 Branch 46 IFNE L969 - false
   * 6 v2.TestFlex.IDY_myphonenr2_click()V: I9 Branch 206 IF_ICMPEQ L4455 - false
   * 7 v2.TestFlex.IDY_myphonenr2_click()V: I13 Branch 207 IFEQ L4456 - true
   * 8 v2.TestFlex.IDY_myphonenr2_click()V: I26 Branch 208 IFNE L4459 - true
   * 9 v2.TestFlex.IDY_myphonenr2_click()V: I141 Branch 209 TABLESWITCH L4491 Case 0 - true
   * 10 v2.TestFlex.IDY_myphonenr2_click()V: I141 Branch 210 TABLESWITCH L4491 Case 1 - false
   * 11 v2.TestFlex.IDY_myphonenr2_click()V: I141 Branch 211 TABLESWITCH L4491 Case 2 - false
   * 12 v2.TestFlex.IDY_myphonenr2_click()V: I141 Branch 212 TABLESWITCH L4491 Default-Case - false
   * 13 v2.TestFlex.IDY_myphonenr2_click()V: I205 Branch 214 IFNE L4554 - false
   */  @Test
  public void test16()  throws Throwable  {
      TestFlex.IDY_myphonenr2_click();
      TestFlex.Image3_click();
  }

  //Test case number: 17
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_myphonenr1_type(I)V: I17 Branch 47 IF_ICMPNE L1029 - true
   * 2 v2.TestFlex.IDY_myphonenr1_type(I)V: I28 Branch 48 IFNE L1032 - false
   */  @Test
  public void test17()  throws Throwable  {
      int int0 = (-24);
      try {
        TestFlex.IDY_myphonenr1_type(int0);
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_myphonenr1_type doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 18
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_myphonenr1_type(I)V: I17 Branch 47 IF_ICMPNE L1029 - false
   * 2 v2.TestFlex.IDY_myphonenr1_type(I)V: I28 Branch 48 IFNE L1032 - true
   * 3 v2.TestFlex.IDY_myphonenr1_type(I)V: I144 Branch 49 TABLESWITCH L1064 Case 2 - true
   * 4 v2.TestFlex.IDY_myphonenr1_type(I)V: I144 Branch 50 TABLESWITCH L1064 Default-Case - false
   * 5 v2.TestFlex.IDY_myphonenr1_type(I)V: I148 Branch 51 IFNE L1080 - false
   */  @Test
  public void test18()  throws Throwable  {
      int int0 = (-11);
      TestFlex.IDY_searchproduct_click();
      TestFlex.IDY_myphonenr1_type(int0);
  }

  //Test case number: 19
  /*
   * 10 covered goals:
   * 1 v2.TestFlex.IDY_addressState_open()V: I9 Branch 52 IF_ICMPEQ L1137 - true
   * 2 v2.TestFlex.IDY_addressState_open()V: I27 Branch 54 IFNE L1141 - true
   * 3 v2.TestFlex.IDY_myphonenr1_click()V: I9 Branch 220 IF_ICMPEQ L4694 - false
   * 4 v2.TestFlex.IDY_myphonenr1_click()V: I13 Branch 221 IFEQ L4695 - true
   * 5 v2.TestFlex.IDY_myphonenr1_click()V: I26 Branch 222 IFNE L4698 - true
   * 6 v2.TestFlex.IDY_myphonenr1_click()V: I141 Branch 223 TABLESWITCH L4730 Case 0 - true
   * 7 v2.TestFlex.IDY_myphonenr1_click()V: I141 Branch 224 TABLESWITCH L4730 Case 1 - false
   * 8 v2.TestFlex.IDY_myphonenr1_click()V: I141 Branch 225 TABLESWITCH L4730 Case 2 - false
   * 9 v2.TestFlex.IDY_myphonenr1_click()V: I141 Branch 226 TABLESWITCH L4730 Default-Case - false
   * 10 v2.TestFlex.IDY_myphonenr1_click()V: I205 Branch 228 IFNE L4789 - false
   */  @Test
  public void test19()  throws Throwable  {
      TestFlex.IDY_myphonenr1_click();
      try {
        TestFlex.IDY_addressState_open();
        fail("Expecting exception: SutCommunicationException");
      } catch(SutCommunicationException e) {
        /*
         * java.lang.RuntimeException: button not visible
         */
      }
  }

  //Test case number: 20
  /*
   * 3 covered goals:
   * 1 v2.TestFlex.IDY_addressState_open()V: I9 Branch 52 IF_ICMPEQ L1137 - false
   * 2 v2.TestFlex.IDY_addressState_open()V: I14 Branch 53 IF_ICMPEQ L1138 - false
   * 3 v2.TestFlex.IDY_addressState_open()V: I27 Branch 54 IFNE L1141 - false
   */  @Test
  public void test20()  throws Throwable  {
      try {
        TestFlex.IDY_addressState_open();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_addressState_open doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 21
  /*
   * 1 covered goal:
   * 1 v2.TestFlex.IDY_addressState_open()V: I14 Branch 53 IF_ICMPEQ L1138 - true
   */  @Test
  public void test21()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      try {
        TestFlex.IDY_addressState_open();
        fail("Expecting exception: SutCommunicationException");
      } catch(SutCommunicationException e) {
        /*
         * java.lang.RuntimeException: button not visible
         */
      }
  }

  //Test case number: 22
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_buttonLogin_click()V: I9 Branch 60 IF_ICMPNE L1303 - true
   * 2 v2.TestFlex.IDY_buttonLogin_click()V: I20 Branch 61 IFNE L1306 - false
   */  @Test
  public void test22()  throws Throwable  {
      try {
        TestFlex.IDY_buttonLogin_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_buttonLogin_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 23
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_buttonLogin_click()V: I9 Branch 60 IF_ICMPNE L1303 - false
   * 2 v2.TestFlex.IDY_buttonLogin_click()V: I20 Branch 61 IFNE L1306 - true
   * 3 v2.TestFlex.IDY_buttonLogin_click()V: I135 Branch 62 TABLESWITCH L1338 Case 2 - true
   * 4 v2.TestFlex.IDY_buttonLogin_click()V: I135 Branch 63 TABLESWITCH L1338 Default-Case - false
   * 5 v2.TestFlex.IDY_buttonLogin_click()V: I139 Branch 64 IFNE L1358 - false
   */  @Test
  public void test23()  throws Throwable  {
      TestFlex.IDY_searchproduct_click();
      TestFlex.IDY_buttonLogin_click();
  }

  //Test case number: 24
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_searchproduct_type(I)V: I17 Branch 65 IF_ICMPNE L1411 - true
   * 2 v2.TestFlex.IDY_searchproduct_type(I)V: I28 Branch 66 IFNE L1414 - false
   */  @Test
  public void test24()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      try {
        TestFlex.IDY_searchproduct_type(int0);
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_searchproduct_type doesn't apply to current state:n4
         */
      }
  }

  //Test case number: 25
  /*
   * 13 covered goals:
   * 1 v2.TestFlex.IDY_searchproduct_type(I)V: I17 Branch 65 IF_ICMPNE L1411 - false
   * 2 v2.TestFlex.IDY_searchproduct_type(I)V: I28 Branch 66 IFNE L1414 - true
   * 3 v2.TestFlex.IDY_searchproduct_type(I)V: I144 Branch 67 TABLESWITCH L1446 Case 2 - true
   * 4 v2.TestFlex.IDY_searchproduct_type(I)V: I144 Branch 68 TABLESWITCH L1446 Default-Case - false
   * 5 v2.TestFlex.IDY_searchproduct_type(I)V: I148 Branch 69 IFNE L1485 - false
   * 6 v2.TestFlex.image0_click()V: I9 Branch 239 IF_ICMPEQ L5041 - false
   * 7 v2.TestFlex.image0_click()V: I13 Branch 240 IFEQ L5042 - true
   * 8 v2.TestFlex.image0_click()V: I31 Branch 242 IFNE L5046 - true
   * 9 v2.TestFlex.image0_click()V: I146 Branch 243 TABLESWITCH L5078 Case 0 - true
   * 10 v2.TestFlex.image0_click()V: I146 Branch 244 TABLESWITCH L5078 Case 1 - false
   * 11 v2.TestFlex.image0_click()V: I146 Branch 245 TABLESWITCH L5078 Case 2 - false
   * 12 v2.TestFlex.image0_click()V: I146 Branch 246 TABLESWITCH L5078 Default-Case - false
   * 13 v2.TestFlex.image0_click()V: I210 Branch 248 IFNE L5140 - false
   */  @Test
  public void test25()  throws Throwable  {
      TestFlex.image0_click();
      int int0 = 9;
      TestFlex.IDY_searchproduct_type(int0);
  }

  //Test case number: 26
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_remove_shoppingCart_5_click()V: I9 Branch 70 IF_ICMPNE L1519 - true
   * 2 v2.TestFlex.IDY_remove_shoppingCart_5_click()V: I20 Branch 71 IFNE L1522 - false
   */  @Test
  public void test26()  throws Throwable  {
      try {
        TestFlex.IDY_remove_shoppingCart_5_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_remove_shoppingCart_5_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 27
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_remove_shoppingCart_5_click()V: I9 Branch 70 IF_ICMPNE L1519 - false
   * 2 v2.TestFlex.IDY_remove_shoppingCart_5_click()V: I20 Branch 71 IFNE L1522 - true
   */  @Test
  public void test27()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_cancas_4_click();
      TestFlex.IDY_purchase_this_click();
      try {
        TestFlex.IDY_remove_shoppingCart_5_click();
        fail("Expecting exception: SutCommunicationException");
      } catch(SutCommunicationException e) {
        /*
         * java.lang.RuntimeException: removeCartButton can't be invoked
         */
      }
  }

  //Test case number: 28
  /*
   * 8 covered goals:
   * 1 v2.TestFlex.IDY_remove_shoppingCart_5_click()V: I135 Branch 72 TABLESWITCH L1554 Case 1 - true
   * 2 v2.TestFlex.IDY_remove_shoppingCart_5_click()V: I135 Branch 73 TABLESWITCH L1554 Default-Case - false
   * 3 v2.TestFlex.IDY_remove_shoppingCart_5_click()V: I139 Branch 74 IFLE L1582 - false
   * 4 v2.TestFlex.IDY_purchase_5_click()V: I9 Branch 191 IF_ICMPNE L4129 - false
   * 5 v2.TestFlex.IDY_purchase_5_click()V: I20 Branch 192 IFNE L4132 - true
   * 6 v2.TestFlex.IDY_purchase_5_click()V: I135 Branch 193 TABLESWITCH L4164 Case 1 - true
   * 7 v2.TestFlex.IDY_purchase_5_click()V: I135 Branch 194 TABLESWITCH L4164 Default-Case - false
   * 8 v2.TestFlex.IDY_purchase_5_click()V: I139 Branch 195 IFLE L4185 - false
   */  @Test
  public void test28()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_purchase_5_click();
      TestFlex.IDY_remove_shoppingCart_5_click();
  }

  //Test case number: 29
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_myphonenr3_type(I)V: I17 Branch 75 IF_ICMPNE L1628 - true
   * 2 v2.TestFlex.IDY_myphonenr3_type(I)V: I28 Branch 76 IFNE L1631 - false
   */  @Test
  public void test29()  throws Throwable  {
      int int0 = 3;
      try {
        TestFlex.IDY_myphonenr3_type(int0);
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_myphonenr3_type doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 30
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_myphonenr3_type(I)V: I17 Branch 75 IF_ICMPNE L1628 - false
   * 2 v2.TestFlex.IDY_myphonenr3_type(I)V: I28 Branch 76 IFNE L1631 - true
   * 3 v2.TestFlex.IDY_myphonenr3_type(I)V: I144 Branch 77 TABLESWITCH L1663 Case 2 - true
   * 4 v2.TestFlex.IDY_myphonenr3_type(I)V: I144 Branch 78 TABLESWITCH L1663 Default-Case - false
   * 5 v2.TestFlex.IDY_myphonenr3_type(I)V: I148 Branch 79 IFNE L1681 - false
   */  @Test
  public void test30()  throws Throwable  {
      TestFlex.IDY_searchproduct_click();
      int int0 = 20;
      TestFlex.IDY_myphonenr3_type(int0);
  }

  //Test case number: 31
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_cancas_5_click()V: I9 Branch 80 IF_ICMPNE L1736 - true
   * 2 v2.TestFlex.IDY_cancas_5_click()V: I20 Branch 81 IFNE L1739 - false
   */  @Test
  public void test31()  throws Throwable  {
      try {
        TestFlex.IDY_cancas_5_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_cancas_5_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 32
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_cancas_5_click()V: I9 Branch 80 IF_ICMPNE L1736 - false
   * 2 v2.TestFlex.IDY_cancas_5_click()V: I20 Branch 81 IFNE L1739 - true
   * 3 v2.TestFlex.IDY_cancas_5_click()V: I135 Branch 82 TABLESWITCH L1771 Case 1 - true
   * 4 v2.TestFlex.IDY_cancas_5_click()V: I135 Branch 83 TABLESWITCH L1771 Default-Case - false
   * 5 v2.TestFlex.IDY_cancas_5_click()V: I139 Branch 84 IFLE L1793 - false
   */  @Test
  public void test32()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_cancas_4_click();
      TestFlex.IDY_purchase_this_click();
      TestFlex.IDY_cancas_5_click();
  }

  //Test case number: 33
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_addressStreet_click()V: I9 Branch 85 IF_ICMPNE L1845 - true
   * 2 v2.TestFlex.IDY_addressStreet_click()V: I20 Branch 86 IFNE L1848 - false
   */  @Test
  public void test33()  throws Throwable  {
      try {
        TestFlex.IDY_addressStreet_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_addressStreet_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 34
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_addressStreet_click()V: I9 Branch 85 IF_ICMPNE L1845 - false
   * 2 v2.TestFlex.IDY_addressStreet_click()V: I20 Branch 86 IFNE L1848 - true
   */  @Test
  public void test34()  throws Throwable  {
      TestFlex.image0_click();
      try {
        TestFlex.IDY_addressStreet_click();
        fail("Expecting exception: SutCommunicationException");
      } catch(SutCommunicationException e) {
        /*
         * java.lang.RuntimeException: button not visible
         */
      }
  }

  //Test case number: 35
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_checkbox_remember_click()V: I9 Branch 90 IF_ICMPNE L1953 - true
   * 2 v2.TestFlex.IDY_checkbox_remember_click()V: I20 Branch 91 IFNE L1956 - false
   */  @Test
  public void test35()  throws Throwable  {
      try {
        TestFlex.IDY_checkbox_remember_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_checkbox_remember_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 36
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_checkbox_remember_click()V: I9 Branch 90 IF_ICMPNE L1953 - false
   * 2 v2.TestFlex.IDY_checkbox_remember_click()V: I20 Branch 91 IFNE L1956 - true
   * 3 v2.TestFlex.IDY_checkbox_remember_click()V: I135 Branch 92 TABLESWITCH L1988 Case 2 - true
   * 4 v2.TestFlex.IDY_checkbox_remember_click()V: I135 Branch 93 TABLESWITCH L1988 Default-Case - false
   * 5 v2.TestFlex.IDY_checkbox_remember_click()V: I139 Branch 94 IFNE L2003 - false
   */  @Test
  public void test36()  throws Throwable  {
      TestFlex.IDY_myphonenr2_click();
      TestFlex.IDY_checkbox_remember_click();
  }

  //Test case number: 37
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_purchase_6_click()V: I9 Branch 95 IF_ICMPNE L2061 - true
   * 2 v2.TestFlex.IDY_purchase_6_click()V: I20 Branch 96 IFNE L2064 - false
   */  @Test
  public void test37()  throws Throwable  {
      try {
        TestFlex.IDY_purchase_6_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_purchase_6_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 38
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_purchase_9_click()V: I9 Branch 100 IF_ICMPNE L2169 - true
   * 2 v2.TestFlex.IDY_purchase_9_click()V: I20 Branch 101 IFNE L2172 - false
   */  @Test
  public void test38()  throws Throwable  {
      try {
        TestFlex.IDY_purchase_9_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_purchase_9_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 39
  /*
   * 10 covered goals:
   * 1 v2.TestFlex.IDY_remove_shoppingCart_9_click()V: I135 Branch 340 TABLESWITCH L7094 Case 1 - true
   * 2 v2.TestFlex.IDY_remove_shoppingCart_9_click()V: I135 Branch 341 TABLESWITCH L7094 Default-Case - false
   * 3 v2.TestFlex.IDY_remove_shoppingCart_9_click()V: I139 Branch 342 IFLE L7121 - false
   * 4 v2.TestFlex.IDY_remove_shoppingCart_9_click()V: I9 Branch 338 IF_ICMPNE L7059 - false
   * 5 v2.TestFlex.IDY_remove_shoppingCart_9_click()V: I20 Branch 339 IFNE L7062 - true
   * 6 v2.TestFlex.IDY_purchase_9_click()V: I9 Branch 100 IF_ICMPNE L2169 - false
   * 7 v2.TestFlex.IDY_purchase_9_click()V: I20 Branch 101 IFNE L2172 - true
   * 8 v2.TestFlex.IDY_purchase_9_click()V: I135 Branch 102 TABLESWITCH L2204 Case 1 - true
   * 9 v2.TestFlex.IDY_purchase_9_click()V: I135 Branch 103 TABLESWITCH L2204 Default-Case - false
   * 10 v2.TestFlex.IDY_purchase_9_click()V: I139 Branch 104 IFLE L2229 - false
   */  @Test
  public void test39()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_cancas_4_click();
      TestFlex.IDY_purchase_this_click();
      TestFlex.IDY_purchase_9_click();
      TestFlex.IDY_remove_shoppingCart_9_click();
  }

  //Test case number: 40
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_quantity_1_type(I)V: I17 Branch 105 IF_ICMPNE L2278 - true
   * 2 v2.TestFlex.IDY_quantity_1_type(I)V: I28 Branch 106 IFNE L2281 - false
   */  @Test
  public void test40()  throws Throwable  {
      int int0 = 8;
      try {
        TestFlex.IDY_quantity_1_type(int0);
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_quantity_1_type doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 41
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_quantity_1_type(I)V: I17 Branch 105 IF_ICMPNE L2278 - false
   * 2 v2.TestFlex.IDY_quantity_1_type(I)V: I28 Branch 106 IFNE L2281 - true
   * 3 v2.TestFlex.IDY_quantity_1_type(I)V: I144 Branch 107 TABLESWITCH L2313 Case 1 - true
   * 4 v2.TestFlex.IDY_quantity_1_type(I)V: I144 Branch 108 TABLESWITCH L2313 Default-Case - false
   * 5 v2.TestFlex.IDY_quantity_1_type(I)V: I148 Branch 109 IFLE L2349 - false
   */  @Test
  public void test41()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_quantity_1_type(int0);
  }

  //Test case number: 42
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_textFeature_13_click()V: I9 Branch 110 IF_ICMPNE L2387 - true
   * 2 v2.TestFlex.IDY_textFeature_13_click()V: I20 Branch 111 IFNE L2390 - false
   */  @Test
  public void test42()  throws Throwable  {
      try {
        TestFlex.IDY_textFeature_13_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_textFeature_13_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 43
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_textFeature_13_click()V: I9 Branch 110 IF_ICMPNE L2387 - false
   * 2 v2.TestFlex.IDY_textFeature_13_click()V: I20 Branch 111 IFNE L2390 - true
   * 3 v2.TestFlex.IDY_textFeature_13_click()V: I135 Branch 112 TABLESWITCH L2422 Case 1 - true
   * 4 v2.TestFlex.IDY_textFeature_13_click()V: I135 Branch 113 TABLESWITCH L2422 Default-Case - false
   * 5 v2.TestFlex.IDY_textFeature_13_click()V: I139 Branch 114 IFLE L2460 - false
   */  @Test
  public void test43()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_textFeature_13_click();
  }

  //Test case number: 44
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_addressStreet_type(I)V: I17 Branch 115 IF_ICMPNE L2496 - true
   * 2 v2.TestFlex.IDY_addressStreet_type(I)V: I28 Branch 116 IFNE L2499 - false
   */  @Test
  public void test44()  throws Throwable  {
      int int0 = 128;
      try {
        TestFlex.IDY_addressStreet_type(int0);
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_addressStreet_type doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 45
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_addressStreet_type(I)V: I17 Branch 115 IF_ICMPNE L2496 - false
   * 2 v2.TestFlex.IDY_addressStreet_type(I)V: I28 Branch 116 IFNE L2499 - true
   */  @Test
  public void test45()  throws Throwable  {
      TestFlex.IDY_searchproduct_click();
      int int0 = 20;
      try {
        TestFlex.IDY_addressStreet_type(int0);
        fail("Expecting exception: SutCommunicationException");
      } catch(SutCommunicationException e) {
        /*
         * java.lang.RuntimeException: button not visible
         */
      }
  }

  //Test case number: 46
  /*
   * 7 covered goals:
   * 1 v2.TestFlex.IDY_labelPrice_1_click()V: I9 Branch 120 IF_ICMPNE L2604 - true
   * 2 v2.TestFlex.IDY_labelPrice_1_click()V: I20 Branch 121 IFNE L2607 - false
   * 3 v2.TestFlex.IDY_purchase_15_click()V: I9 Branch 343 IF_ICMPNE L7168 - false
   * 4 v2.TestFlex.IDY_purchase_15_click()V: I20 Branch 344 IFNE L7171 - true
   * 5 v2.TestFlex.IDY_purchase_15_click()V: I135 Branch 345 TABLESWITCH L7203 Case 2 - true
   * 6 v2.TestFlex.IDY_purchase_15_click()V: I135 Branch 346 TABLESWITCH L7203 Default-Case - false
   * 7 v2.TestFlex.IDY_purchase_15_click()V: I139 Branch 347 IFLE L7245 - false
   */  @Test
  public void test46()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_15_click();
      try {
        TestFlex.IDY_labelPrice_1_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_labelPrice_1_click doesn't apply to current state:n4
         */
      }
  }

  //Test case number: 47
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_labelPrice_1_click()V: I9 Branch 120 IF_ICMPNE L2604 - false
   * 2 v2.TestFlex.IDY_labelPrice_1_click()V: I20 Branch 121 IFNE L2607 - true
   */  @Test
  public void test47()  throws Throwable  {
      TestFlex.IDY_myphonenr2_click();
      try {
        TestFlex.IDY_labelPrice_1_click();
        fail("Expecting exception: SutCommunicationException");
      } catch(SutCommunicationException e) {
        /*
         * java.lang.RuntimeException: button not visible
         */
      }
  }

  //Test case number: 48
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_addressZip_click()V: I9 Branch 181 IF_ICMPNE L3911 - false
   * 2 v2.TestFlex.IDY_addressZip_click()V: I20 Branch 182 IFNE L3914 - true
   * 3 v2.TestFlex.IDY_labelPrice_1_click()V: I135 Branch 122 TABLESWITCH L2639 Case 2 - true
   * 4 v2.TestFlex.IDY_labelPrice_1_click()V: I135 Branch 123 TABLESWITCH L2639 Default-Case - false
   * 5 v2.TestFlex.IDY_labelPrice_1_click()V: I139 Branch 124 IFNE L2663 - false
   */  @Test
  public void test48()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_labelPrice_1_click();
      TestFlex.IDY_purchase_this_click();
      try {
        TestFlex.IDY_addressZip_click();
        fail("Expecting exception: SutCommunicationException");
      } catch(SutCommunicationException e) {
        /*
         * java.lang.RuntimeException: button not visible
         */
      }
  }

  //Test case number: 49
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_pwd_type(I)V: I17 Branch 125 IF_ICMPNE L2712 - true
   * 2 v2.TestFlex.IDY_pwd_type(I)V: I28 Branch 126 IFNE L2715 - false
   */  @Test
  public void test49()  throws Throwable  {
      int int0 = 1144;
      try {
        TestFlex.IDY_pwd_type(int0);
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_pwd_type doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 50
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_pwd_type(I)V: I17 Branch 125 IF_ICMPNE L2712 - false
   * 2 v2.TestFlex.IDY_pwd_type(I)V: I28 Branch 126 IFNE L2715 - true
   * 3 v2.TestFlex.IDY_pwd_type(I)V: I144 Branch 127 TABLESWITCH L2747 Case 2 - true
   * 4 v2.TestFlex.IDY_pwd_type(I)V: I144 Branch 128 TABLESWITCH L2747 Default-Case - false
   * 5 v2.TestFlex.IDY_pwd_type(I)V: I148 Branch 129 IFNE L2766 - false
   */  @Test
  public void test50()  throws Throwable  {
      int int0 = (-11);
      TestFlex.IDY_searchproduct_click();
      TestFlex.IDY_pwd_type(int0);
  }

  //Test case number: 51
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_buttonLocate_click()V: I9 Branch 130 IF_ICMPNE L2820 - true
   * 2 v2.TestFlex.IDY_buttonLocate_click()V: I20 Branch 131 IFNE L2823 - false
   */  @Test
  public void test51()  throws Throwable  {
      try {
        TestFlex.IDY_buttonLocate_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_buttonLocate_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 52
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_buttonLocate_click()V: I9 Branch 130 IF_ICMPNE L2820 - false
   * 2 v2.TestFlex.IDY_buttonLocate_click()V: I20 Branch 131 IFNE L2823 - true
   */  @Test
  public void test52()  throws Throwable  {
      TestFlex.IDY_searchproduct_click();
      try {
        TestFlex.IDY_buttonLocate_click();
        fail("Expecting exception: SutCommunicationException");
      } catch(SutCommunicationException e) {
        /*
         * java.lang.RuntimeException: button not visible
         */
      }
  }

  //Test case number: 53
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.back_thumb_click()V: I9 Branch 135 IF_ICMPNE L2928 - true
   * 2 v2.TestFlex.back_thumb_click()V: I20 Branch 136 IFNE L2931 - false
   */  @Test
  public void test53()  throws Throwable  {
      try {
        TestFlex.back_thumb_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * back_thumb_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 54
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.back_thumb_click()V: I9 Branch 135 IF_ICMPNE L2928 - false
   * 2 v2.TestFlex.back_thumb_click()V: I20 Branch 136 IFNE L2931 - true
   * 3 v2.TestFlex.back_thumb_click()V: I135 Branch 137 TABLESWITCH L2963 Case 2 - true
   * 4 v2.TestFlex.back_thumb_click()V: I135 Branch 138 TABLESWITCH L2963 Default-Case - false
   * 5 v2.TestFlex.back_thumb_click()V: I139 Branch 139 IFNE L2993 - false
   */  @Test
  public void test54()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.back_thumb_click();
  }

  //Test case number: 55
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_purchase_14_click()V: I9 Branch 140 IF_ICMPNE L3036 - true
   * 2 v2.TestFlex.IDY_purchase_14_click()V: I20 Branch 141 IFNE L3039 - false
   */  @Test
  public void test55()  throws Throwable  {
      try {
        TestFlex.IDY_purchase_14_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_purchase_14_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 56
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_purchase_14_click()V: I9 Branch 140 IF_ICMPNE L3036 - false
   * 2 v2.TestFlex.IDY_purchase_14_click()V: I20 Branch 141 IFNE L3039 - true
   * 3 v2.TestFlex.IDY_purchase_14_click()V: I135 Branch 142 TABLESWITCH L3071 Case 1 - true
   * 4 v2.TestFlex.IDY_purchase_14_click()V: I135 Branch 143 TABLESWITCH L3071 Default-Case - false
   * 5 v2.TestFlex.IDY_purchase_14_click()V: I139 Branch 144 IFLE L3114 - false
   */  @Test
  public void test56()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_cancas_4_click();
      TestFlex.IDY_purchase_this_click();
      TestFlex.IDY_purchase_14_click();
  }

  //Test case number: 57
  /*
   * 3 covered goals:
   * 1 v2.TestFlex.IDY_cancas_4_click()V: I9 Branch 145 IF_ICMPEQ L3145 - false
   * 2 v2.TestFlex.IDY_cancas_4_click()V: I14 Branch 146 IF_ICMPEQ L3146 - false
   * 3 v2.TestFlex.IDY_cancas_4_click()V: I27 Branch 147 IFNE L3149 - false
   */  @Test
  public void test57()  throws Throwable  {
      try {
        TestFlex.IDY_cancas_4_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_cancas_4_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 58
  /*
   * 4 covered goals:
   * 1 v2.TestFlex.IDY_cancas_4_click()V: I14 Branch 146 IF_ICMPEQ L3146 - true
   * 2 v2.TestFlex.IDY_cancas_4_click()V: I142 Branch 148 TABLESWITCH L3181 Case 1 - true
   * 3 v2.TestFlex.IDY_cancas_4_click()V: I142 Branch 149 TABLESWITCH L3181 Case 2 - false
   * 4 v2.TestFlex.IDY_cancas_4_click()V: I206 Branch 152 IFLE L3257 - false
   */  @Test
  public void test58()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_cancas_4_click();
  }

  //Test case number: 59
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.Image6_click()V: I9 Branch 153 IF_ICMPNE L3311 - true
   * 2 v2.TestFlex.Image6_click()V: I20 Branch 154 IFNE L3314 - false
   */  @Test
  public void test59()  throws Throwable  {
      try {
        TestFlex.Image6_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * Image6_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 60
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.Image6_click()V: I9 Branch 153 IF_ICMPNE L3311 - false
   * 2 v2.TestFlex.Image6_click()V: I20 Branch 154 IFNE L3314 - true
   */  @Test
  public void test60()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      try {
        TestFlex.Image6_click();
        fail("Expecting exception: SutCommunicationException");
      } catch(SutCommunicationException e) {
        /*
         * java.lang.RuntimeException: button not visible
         */
      }
  }

  //Test case number: 61
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_cancas_2_click()V: I9 Branch 158 IF_ICMPNE L3420 - true
   * 2 v2.TestFlex.IDY_cancas_2_click()V: I20 Branch 159 IFNE L3423 - false
   */  @Test
  public void test61()  throws Throwable  {
      try {
        TestFlex.IDY_cancas_2_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_cancas_2_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 62
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_cancas_2_click()V: I9 Branch 158 IF_ICMPNE L3420 - false
   * 2 v2.TestFlex.IDY_cancas_2_click()V: I20 Branch 159 IFNE L3423 - true
   * 3 v2.TestFlex.IDY_cancas_2_click()V: I135 Branch 160 TABLESWITCH L3455 Case 1 - true
   * 4 v2.TestFlex.IDY_cancas_2_click()V: I135 Branch 161 TABLESWITCH L3455 Default-Case - false
   * 5 v2.TestFlex.IDY_cancas_2_click()V: I139 Branch 162 IFLE L3471 - false
   */  @Test
  public void test62()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_cancas_2_click();
  }

  //Test case number: 63
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_myphonenr2_type(I)V: I17 Branch 163 IF_ICMPNE L3529 - true
   * 2 v2.TestFlex.IDY_myphonenr2_type(I)V: I28 Branch 164 IFNE L3532 - false
   */  @Test
  public void test63()  throws Throwable  {
      int int0 = (-15);
      try {
        TestFlex.IDY_myphonenr2_type(int0);
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_myphonenr2_type doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 64
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_myphonenr2_type(I)V: I17 Branch 163 IF_ICMPNE L3529 - false
   * 2 v2.TestFlex.IDY_myphonenr2_type(I)V: I28 Branch 164 IFNE L3532 - true
   * 3 v2.TestFlex.IDY_myphonenr2_type(I)V: I144 Branch 165 TABLESWITCH L3564 Case 2 - true
   * 4 v2.TestFlex.IDY_myphonenr2_type(I)V: I144 Branch 166 TABLESWITCH L3564 Default-Case - false
   * 5 v2.TestFlex.IDY_myphonenr2_type(I)V: I148 Branch 167 IFNE L3581 - false
   */  @Test
  public void test64()  throws Throwable  {
      int int0 = (-11);
      TestFlex.IDY_myphonenr2_click();
      TestFlex.IDY_myphonenr2_type(int0);
  }

  //Test case number: 65
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_labelPrice_15_click()V: I9 Branch 168 IF_ICMPNE L3637 - true
   * 2 v2.TestFlex.IDY_labelPrice_15_click()V: I20 Branch 169 IFNE L3640 - false
   */  @Test
  public void test65()  throws Throwable  {
      try {
        TestFlex.IDY_labelPrice_15_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_labelPrice_15_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 66
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_cancas_15_click()V: I9 Branch 173 IF_ICMPEQ L3745 - true
   * 2 v2.TestFlex.IDY_cancas_15_click()V: I27 Branch 175 IFNE L3749 - true
   */  @Test
  public void test66()  throws Throwable  {
      TestFlex.IDY_myphonenr2_click();
      try {
        TestFlex.IDY_cancas_15_click();
        fail("Expecting exception: SutCommunicationException");
      } catch(SutCommunicationException e) {
        /*
         * java.lang.RuntimeException: button not visible
         */
      }
  }

  //Test case number: 67
  /*
   * 3 covered goals:
   * 1 v2.TestFlex.IDY_cancas_15_click()V: I9 Branch 173 IF_ICMPEQ L3745 - false
   * 2 v2.TestFlex.IDY_cancas_15_click()V: I14 Branch 174 IF_ICMPEQ L3746 - false
   * 3 v2.TestFlex.IDY_cancas_15_click()V: I27 Branch 175 IFNE L3749 - false
   */  @Test
  public void test67()  throws Throwable  {
      try {
        TestFlex.IDY_cancas_15_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_cancas_15_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 68
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_cancas_15_click()V: I14 Branch 174 IF_ICMPEQ L3746 - true
   * 2 v2.TestFlex.IDY_cancas_15_click()V: I142 Branch 176 TABLESWITCH L3781 Case 1 - true
   * 3 v2.TestFlex.IDY_cancas_15_click()V: I142 Branch 177 TABLESWITCH L3781 Case 2 - false
   * 4 v2.TestFlex.IDY_cancas_15_click()V: I142 Branch 178 TABLESWITCH L3781 Default-Case - false
   * 5 v2.TestFlex.IDY_cancas_15_click()V: I206 Branch 180 IFLE L3874 - false
   */  @Test
  public void test68()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_cancas_4_click();
      TestFlex.IDY_purchase_this_click();
      TestFlex.IDY_cancas_15_click();
  }

  //Test case number: 69
  /*
   * 3 covered goals:
   * 1 v2.TestFlex.IDY_cancas_15_click()V: I142 Branch 176 TABLESWITCH L3781 Case 1 - false
   * 2 v2.TestFlex.IDY_cancas_15_click()V: I142 Branch 177 TABLESWITCH L3781 Case 2 - true
   * 3 v2.TestFlex.IDY_cancas_15_click()V: I146 Branch 179 IFNE L3822 - false
   */  @Test
  public void test69()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_cancas_15_click();
  }

  //Test case number: 70
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_addressZip_click()V: I9 Branch 181 IF_ICMPNE L3911 - true
   * 2 v2.TestFlex.IDY_addressZip_click()V: I20 Branch 182 IFNE L3914 - false
   */  @Test
  public void test70()  throws Throwable  {
      try {
        TestFlex.IDY_addressZip_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_addressZip_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 71
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_remove_shoppingCart_3_click()V: I9 Branch 186 IF_ICMPNE L4020 - true
   * 2 v2.TestFlex.IDY_remove_shoppingCart_3_click()V: I20 Branch 187 IFNE L4023 - false
   */  @Test
  public void test71()  throws Throwable  {
      try {
        TestFlex.IDY_remove_shoppingCart_3_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_remove_shoppingCart_3_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 72
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_remove_shoppingCart_3_click()V: I9 Branch 186 IF_ICMPNE L4020 - false
   * 2 v2.TestFlex.IDY_remove_shoppingCart_3_click()V: I20 Branch 187 IFNE L4023 - true
   */  @Test
  public void test72()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      try {
        TestFlex.IDY_remove_shoppingCart_3_click();
        fail("Expecting exception: SutCommunicationException");
      } catch(SutCommunicationException e) {
        /*
         * java.lang.RuntimeException: removeCartButton can't be invoked
         */
      }
  }

  //Test case number: 73
  /*
   * 3 covered goals:
   * 1 v2.TestFlex.IDY_remove_shoppingCart_3_click()V: I135 Branch 188 TABLESWITCH L4055 Case 1 - true
   * 2 v2.TestFlex.IDY_remove_shoppingCart_3_click()V: I135 Branch 189 TABLESWITCH L4055 Default-Case - false
   * 3 v2.TestFlex.IDY_remove_shoppingCart_3_click()V: I139 Branch 190 IFLE L4085 - false
   */  @Test
  public void test73()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_purchase_3_click();
      TestFlex.IDY_remove_shoppingCart_3_click();
  }

  //Test case number: 74
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_purchase_5_click()V: I9 Branch 191 IF_ICMPNE L4129 - true
   * 2 v2.TestFlex.IDY_purchase_5_click()V: I20 Branch 192 IFNE L4132 - false
   */  @Test
  public void test74()  throws Throwable  {
      try {
        TestFlex.IDY_purchase_5_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_purchase_5_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 75
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_cancas_7_click()V: I9 Branch 196 IF_ICMPNE L4238 - true
   * 2 v2.TestFlex.IDY_cancas_7_click()V: I20 Branch 197 IFNE L4241 - false
   */  @Test
  public void test75()  throws Throwable  {
      try {
        TestFlex.IDY_cancas_7_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_cancas_7_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 76
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_cancas_7_click()V: I9 Branch 196 IF_ICMPNE L4238 - false
   * 2 v2.TestFlex.IDY_cancas_7_click()V: I20 Branch 197 IFNE L4241 - true
   * 3 v2.TestFlex.IDY_cancas_7_click()V: I135 Branch 198 TABLESWITCH L4273 Case 1 - true
   * 4 v2.TestFlex.IDY_cancas_7_click()V: I135 Branch 199 TABLESWITCH L4273 Default-Case - false
   * 5 v2.TestFlex.IDY_cancas_7_click()V: I139 Branch 200 IFLE L4278 - false
   */  @Test
  public void test76()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_6_click();
      TestFlex.IDY_cancas_7_click();
  }

  //Test case number: 77
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_pwd_click()V: I9 Branch 201 IF_ICMPNE L4347 - true
   * 2 v2.TestFlex.IDY_pwd_click()V: I20 Branch 202 IFNE L4350 - false
   */  @Test
  public void test77()  throws Throwable  {
      try {
        TestFlex.IDY_pwd_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_pwd_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 78
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_pwd_click()V: I9 Branch 201 IF_ICMPNE L4347 - false
   * 2 v2.TestFlex.IDY_pwd_click()V: I20 Branch 202 IFNE L4350 - true
   * 3 v2.TestFlex.IDY_pwd_click()V: I135 Branch 203 TABLESWITCH L4382 Case 2 - true
   * 4 v2.TestFlex.IDY_pwd_click()V: I135 Branch 204 TABLESWITCH L4382 Default-Case - false
   * 5 v2.TestFlex.IDY_pwd_click()V: I139 Branch 205 IFNE L4389 - false
   */  @Test
  public void test78()  throws Throwable  {
      TestFlex.IDY_myphonenr2_click();
      TestFlex.IDY_pwd_click();
  }

  //Test case number: 79
  /*
   * 4 covered goals:
   * 1 v2.TestFlex.IDY_myphonenr2_click()V: I9 Branch 206 IF_ICMPEQ L4455 - true
   * 2 v2.TestFlex.IDY_myphonenr2_click()V: I141 Branch 209 TABLESWITCH L4491 Case 0 - false
   * 3 v2.TestFlex.IDY_myphonenr2_click()V: I141 Branch 211 TABLESWITCH L4491 Case 2 - true
   * 4 v2.TestFlex.IDY_myphonenr2_click()V: I145 Branch 213 IFNE L4494 - false
   */  @Test
  public void test79()  throws Throwable  {
      TestFlex.IDY_myphonenr2_click();
      TestFlex.IDY_myphonenr2_click();
  }

  //Test case number: 80
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_myphonenr2_click()V: I13 Branch 207 IFEQ L4456 - false
   * 2 v2.TestFlex.IDY_myphonenr2_click()V: I26 Branch 208 IFNE L4459 - false
   */  @Test
  public void test80()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      try {
        TestFlex.IDY_myphonenr2_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_myphonenr2_click doesn't apply to current state:n4
         */
      }
  }

  //Test case number: 81
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_purchase_13_click()V: I9 Branch 215 IF_ICMPNE L4585 - true
   * 2 v2.TestFlex.IDY_purchase_13_click()V: I20 Branch 216 IFNE L4588 - false
   */  @Test
  public void test81()  throws Throwable  {
      try {
        TestFlex.IDY_purchase_13_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_purchase_13_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 82
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_purchase_13_click()V: I9 Branch 215 IF_ICMPNE L4585 - false
   * 2 v2.TestFlex.IDY_purchase_13_click()V: I20 Branch 216 IFNE L4588 - true
   * 3 v2.TestFlex.IDY_purchase_13_click()V: I135 Branch 217 TABLESWITCH L4620 Case 1 - true
   * 4 v2.TestFlex.IDY_purchase_13_click()V: I135 Branch 218 TABLESWITCH L4620 Default-Case - false
   * 5 v2.TestFlex.IDY_purchase_13_click()V: I139 Branch 219 IFLE L4660 - false
   */  @Test
  public void test82()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_purchase_13_click();
  }

  //Test case number: 83
  /*
   * 4 covered goals:
   * 1 v2.TestFlex.IDY_myphonenr1_click()V: I9 Branch 220 IF_ICMPEQ L4694 - true
   * 2 v2.TestFlex.IDY_myphonenr1_click()V: I141 Branch 223 TABLESWITCH L4730 Case 0 - false
   * 3 v2.TestFlex.IDY_myphonenr1_click()V: I141 Branch 225 TABLESWITCH L4730 Case 2 - true
   * 4 v2.TestFlex.IDY_myphonenr1_click()V: I145 Branch 227 IFNE L4736 - false
   */  @Test
  public void test83()  throws Throwable  {
      TestFlex.IDY_myphonenr1_click();
      TestFlex.IDY_myphonenr1_click();
  }

  //Test case number: 84
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_myphonenr1_click()V: I13 Branch 221 IFEQ L4695 - false
   * 2 v2.TestFlex.IDY_myphonenr1_click()V: I26 Branch 222 IFNE L4698 - false
   */  @Test
  public void test84()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_15_click();
      try {
        TestFlex.IDY_myphonenr1_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_myphonenr1_click doesn't apply to current state:n4
         */
      }
  }

  //Test case number: 85
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_purchase_4_click()V: I9 Branch 229 IF_ICMPNE L4824 - true
   * 2 v2.TestFlex.IDY_purchase_4_click()V: I20 Branch 230 IFNE L4827 - false
   */  @Test
  public void test85()  throws Throwable  {
      try {
        TestFlex.IDY_purchase_4_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_purchase_4_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 86
  /*
   * 10 covered goals:
   * 1 v2.TestFlex.IDY_remove_shoppingCart_4_click()V: I135 Branch 307 TABLESWITCH L6384 Case 1 - true
   * 2 v2.TestFlex.IDY_remove_shoppingCart_4_click()V: I135 Branch 308 TABLESWITCH L6384 Default-Case - false
   * 3 v2.TestFlex.IDY_remove_shoppingCart_4_click()V: I139 Branch 309 IFLE L6413 - false
   * 4 v2.TestFlex.IDY_purchase_4_click()V: I9 Branch 229 IF_ICMPNE L4824 - false
   * 5 v2.TestFlex.IDY_purchase_4_click()V: I20 Branch 230 IFNE L4827 - true
   * 6 v2.TestFlex.IDY_purchase_4_click()V: I135 Branch 231 TABLESWITCH L4859 Case 1 - true
   * 7 v2.TestFlex.IDY_purchase_4_click()V: I135 Branch 232 TABLESWITCH L4859 Default-Case - false
   * 8 v2.TestFlex.IDY_purchase_4_click()V: I139 Branch 233 IFLE L4878 - false
   * 9 v2.TestFlex.IDY_remove_shoppingCart_4_click()V: I9 Branch 305 IF_ICMPNE L6349 - false
   * 10 v2.TestFlex.IDY_remove_shoppingCart_4_click()V: I20 Branch 306 IFNE L6352 - true
   */  @Test
  public void test86()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_purchase_4_click();
      TestFlex.IDY_remove_shoppingCart_4_click();
  }

  //Test case number: 87
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.OK_click()V: I9 Branch 234 IF_ICMPNE L4933 - true
   * 2 v2.TestFlex.OK_click()V: I20 Branch 235 IFNE L4936 - false
   */  @Test
  public void test87()  throws Throwable  {
      try {
        TestFlex.OK_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * OK_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 88
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.OK_click()V: I9 Branch 234 IF_ICMPNE L4933 - false
   * 2 v2.TestFlex.OK_click()V: I20 Branch 235 IFNE L4936 - true
   * 3 v2.TestFlex.OK_click()V: I135 Branch 236 TABLESWITCH L4968 Case 2 - true
   * 4 v2.TestFlex.OK_click()V: I135 Branch 237 TABLESWITCH L4968 Default-Case - false
   * 5 v2.TestFlex.OK_click()V: I139 Branch 238 IFNE L4980 - false
   */  @Test
  public void test88()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.OK_click();
  }

  //Test case number: 89
  /*
   * 4 covered goals:
   * 1 v2.TestFlex.image0_click()V: I9 Branch 239 IF_ICMPEQ L5041 - true
   * 2 v2.TestFlex.image0_click()V: I146 Branch 243 TABLESWITCH L5078 Case 0 - false
   * 3 v2.TestFlex.image0_click()V: I146 Branch 245 TABLESWITCH L5078 Case 2 - true
   * 4 v2.TestFlex.image0_click()V: I150 Branch 247 IFNE L5086 - false
   */  @Test
  public void test89()  throws Throwable  {
      TestFlex.IDY_myphonenr2_click();
      TestFlex.image0_click();
  }

  //Test case number: 90
  /*
   * 4 covered goals:
   * 1 v2.TestFlex.image0_click()V: I13 Branch 240 IFEQ L5042 - false
   * 2 v2.TestFlex.image0_click()V: I18 Branch 241 IF_ICMPEQ L5043 - true
   * 3 v2.TestFlex.image0_click()V: I146 Branch 244 TABLESWITCH L5078 Case 1 - true
   * 4 v2.TestFlex.image0_click()V: I270 Branch 249 IFLE L5169 - false
   */  @Test
  public void test90()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_6_click();
      TestFlex.image0_click();
  }

  //Test case number: 91
  /*
   * 3 covered goals:
   * 1 v2.TestFlex.IDY_purchase_1_click()V: I9 Branch 250 IF_ICMPEQ L5229 - false
   * 2 v2.TestFlex.IDY_purchase_1_click()V: I14 Branch 251 IF_ICMPEQ L5230 - false
   * 3 v2.TestFlex.IDY_purchase_1_click()V: I27 Branch 252 IFNE L5233 - false
   */  @Test
  public void test91()  throws Throwable  {
      try {
        TestFlex.IDY_purchase_1_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_purchase_1_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 92
  /*
   * 4 covered goals:
   * 1 v2.TestFlex.IDY_purchase_1_click()V: I14 Branch 251 IF_ICMPEQ L5230 - true
   * 2 v2.TestFlex.IDY_purchase_1_click()V: I142 Branch 253 TABLESWITCH L5265 Case 1 - true
   * 3 v2.TestFlex.IDY_purchase_1_click()V: I142 Branch 254 TABLESWITCH L5265 Case 2 - false
   * 4 v2.TestFlex.IDY_purchase_1_click()V: I206 Branch 257 IFLE L5353 - false
   */  @Test
  public void test92()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_purchase_1_click();
  }

  //Test case number: 93
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_purchase_12_click()V: I9 Branch 258 IF_ICMPNE L5395 - true
   * 2 v2.TestFlex.IDY_purchase_12_click()V: I20 Branch 259 IFNE L5398 - false
   */  @Test
  public void test93()  throws Throwable  {
      try {
        TestFlex.IDY_purchase_12_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_purchase_12_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 94
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_purchase_12_click()V: I9 Branch 258 IF_ICMPNE L5395 - false
   * 2 v2.TestFlex.IDY_purchase_12_click()V: I20 Branch 259 IFNE L5398 - true
   * 3 v2.TestFlex.IDY_purchase_12_click()V: I135 Branch 260 TABLESWITCH L5430 Case 1 - true
   * 4 v2.TestFlex.IDY_purchase_12_click()V: I135 Branch 261 TABLESWITCH L5430 Default-Case - false
   * 5 v2.TestFlex.IDY_purchase_12_click()V: I139 Branch 262 IFLE L5436 - false
   */  @Test
  public void test94()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_purchase_12_click();
  }

  //Test case number: 95
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.Image7_click()V: I9 Branch 263 IF_ICMPEQ L5504 - true
   * 2 v2.TestFlex.Image7_click()V: I27 Branch 265 IFNE L5508 - true
   */  @Test
  public void test95()  throws Throwable  {
      TestFlex.IDY_myphonenr2_click();
      try {
        TestFlex.Image7_click();
        fail("Expecting exception: SutCommunicationException");
      } catch(SutCommunicationException e) {
        /*
         * java.lang.RuntimeException: button not visible
         */
      }
  }

  //Test case number: 96
  /*
   * 3 covered goals:
   * 1 v2.TestFlex.Image7_click()V: I9 Branch 263 IF_ICMPEQ L5504 - false
   * 2 v2.TestFlex.Image7_click()V: I14 Branch 264 IF_ICMPEQ L5505 - false
   * 3 v2.TestFlex.Image7_click()V: I27 Branch 265 IFNE L5508 - false
   */  @Test
  public void test96()  throws Throwable  {
      try {
        TestFlex.Image7_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * Image7_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 97
  /*
   * 1 covered goal:
   * 1 v2.TestFlex.Image7_click()V: I14 Branch 264 IF_ICMPEQ L5505 - true
   */  @Test
  public void test97()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      try {
        TestFlex.Image7_click();
        fail("Expecting exception: SutCommunicationException");
      } catch(SutCommunicationException e) {
        /*
         * java.lang.RuntimeException: button not visible
         */
      }
  }

  //Test case number: 98
  /*
   * 6 covered goals:
   * 1 v2.TestFlex.IDY_cancas_12_click()V: I9 Branch 271 IF_ICMPEQ L5670 - true
   * 2 v2.TestFlex.IDY_cancas_12_click()V: I27 Branch 273 IFNE L5674 - true
   * 3 v2.TestFlex.IDY_cancas_12_click()V: I142 Branch 274 TABLESWITCH L5706 Case 1 - false
   * 4 v2.TestFlex.IDY_cancas_12_click()V: I142 Branch 275 TABLESWITCH L5706 Case 2 - true
   * 5 v2.TestFlex.IDY_cancas_12_click()V: I142 Branch 276 TABLESWITCH L5706 Default-Case - false
   * 6 v2.TestFlex.IDY_cancas_12_click()V: I146 Branch 277 IFNE L5738 - false
   */  @Test
  public void test98()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_cancas_12_click();
  }

  //Test case number: 99
  /*
   * 3 covered goals:
   * 1 v2.TestFlex.IDY_cancas_12_click()V: I9 Branch 271 IF_ICMPEQ L5670 - false
   * 2 v2.TestFlex.IDY_cancas_12_click()V: I14 Branch 272 IF_ICMPEQ L5671 - false
   * 3 v2.TestFlex.IDY_cancas_12_click()V: I27 Branch 273 IFNE L5674 - false
   */  @Test
  public void test99()  throws Throwable  {
      try {
        TestFlex.IDY_cancas_12_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_cancas_12_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 100
  /*
   * 4 covered goals:
   * 1 v2.TestFlex.IDY_cancas_12_click()V: I14 Branch 272 IF_ICMPEQ L5671 - true
   * 2 v2.TestFlex.IDY_cancas_12_click()V: I142 Branch 274 TABLESWITCH L5706 Case 1 - true
   * 3 v2.TestFlex.IDY_cancas_12_click()V: I142 Branch 275 TABLESWITCH L5706 Case 2 - false
   * 4 v2.TestFlex.IDY_cancas_12_click()V: I206 Branch 278 IFLE L5769 - false
   */  @Test
  public void test100()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_cancas_12_click();
  }

  //Test case number: 101
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_VideoButton_click()V: I9 Branch 279 IF_ICMPNE L5836 - true
   * 2 v2.TestFlex.IDY_VideoButton_click()V: I20 Branch 280 IFNE L5839 - false
   */  @Test
  public void test101()  throws Throwable  {
      try {
        TestFlex.IDY_VideoButton_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_VideoButton_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 102
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_VideoButton_click()V: I9 Branch 279 IF_ICMPNE L5836 - false
   * 2 v2.TestFlex.IDY_VideoButton_click()V: I20 Branch 280 IFNE L5839 - true
   */  @Test
  public void test102()  throws Throwable  {
      TestFlex.IDY_myphonenr2_click();
      try {
        TestFlex.IDY_VideoButton_click();
        fail("Expecting exception: SutCommunicationException");
      } catch(SutCommunicationException e) {
        /*
         * java.lang.RuntimeException: button not visible
         */
      }
  }

  //Test case number: 103
  /*
   * 3 covered goals:
   * 1 v2.TestFlex.IDY_VideoButton_click()V: I135 Branch 281 TABLESWITCH L5871 Case 2 - true
   * 2 v2.TestFlex.IDY_VideoButton_click()V: I135 Branch 282 TABLESWITCH L5871 Default-Case - false
   * 3 v2.TestFlex.IDY_VideoButton_click()V: I139 Branch 283 IFNE L5900 - false
   */  @Test
  public void test103()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_cancas_4_click();
      TestFlex.IDY_VideoButton_click();
  }

  //Test case number: 104
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_purchase_this_click()V: I9 Branch 284 IF_ICMPNE L5944 - true
   * 2 v2.TestFlex.IDY_purchase_this_click()V: I20 Branch 285 IFNE L5947 - false
   */  @Test
  public void test104()  throws Throwable  {
      try {
        TestFlex.IDY_purchase_this_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_purchase_this_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 105
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_remove_shoppingCart_1_click()V: I9 Branch 289 IF_ICMPNE L6052 - true
   * 2 v2.TestFlex.IDY_remove_shoppingCart_1_click()V: I20 Branch 290 IFNE L6055 - false
   */  @Test
  public void test105()  throws Throwable  {
      try {
        TestFlex.IDY_remove_shoppingCart_1_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_remove_shoppingCart_1_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 106
  /*
   * 1 covered goal:
   * 1 v2.TestFlex.IDY_remove_shoppingCart_1_click()V: I139 Branch 293 IFNE L6122 - true
   */  @Test
  public void test106()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_purchase_5_click();
      try {
        TestFlex.IDY_remove_shoppingCart_1_click();
        fail("Expecting exception: UnderSpecifiedException");
      } catch(UnderSpecifiedException e) {
        /*
         * in state n4, unexpected target state for mutator: IDY_remove_shoppingCart_1_click sut.state(selectedProduct=-1 numInShopCart=1 )
         */
      }
  }

  //Test case number: 107
  /*
   * 4 covered goals:
   * 1 v2.TestFlex.ButtonBar0_itemclick(I)V: I17 Branch 294 IF_ICMPEQ L6161 - true
   * 2 v2.TestFlex.ButtonBar0_itemclick(I)V: I155 Branch 298 TABLESWITCH L6198 Case 0 - false
   * 3 v2.TestFlex.ButtonBar0_itemclick(I)V: I155 Branch 300 TABLESWITCH L6198 Case 2 - true
   * 4 v2.TestFlex.ButtonBar0_itemclick(I)V: I159 Branch 302 IFNE L6203 - false
   */  @Test
  public void test107()  throws Throwable  {
      TestFlex.IDY_myphonenr2_click();
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
  }

  //Test case number: 108
  /*
   * 4 covered goals:
   * 1 v2.TestFlex.ButtonBar0_itemclick(I)V: I21 Branch 295 IFEQ L6162 - false
   * 2 v2.TestFlex.ButtonBar0_itemclick(I)V: I26 Branch 296 IF_ICMPEQ L6163 - true
   * 3 v2.TestFlex.ButtonBar0_itemclick(I)V: I155 Branch 299 TABLESWITCH L6198 Case 1 - true
   * 4 v2.TestFlex.ButtonBar0_itemclick(I)V: I279 Branch 304 IFLE L6283 - false
   */  @Test
  public void test108()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_cancas_4_click();
      TestFlex.IDY_purchase_this_click();
      TestFlex.ButtonBar0_itemclick(int0);
  }

  //Test case number: 109
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_remove_shoppingCart_4_click()V: I9 Branch 305 IF_ICMPNE L6349 - true
   * 2 v2.TestFlex.IDY_remove_shoppingCart_4_click()V: I20 Branch 306 IFNE L6352 - false
   */  @Test
  public void test109()  throws Throwable  {
      try {
        TestFlex.IDY_remove_shoppingCart_4_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_remove_shoppingCart_4_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 110
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_remove_shoppingCart_4_click()V: I9 Branch 305 IF_ICMPNE L6349 - false
   * 2 v2.TestFlex.IDY_remove_shoppingCart_4_click()V: I20 Branch 306 IFNE L6352 - true
   */  @Test
  public void test110()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      try {
        TestFlex.IDY_remove_shoppingCart_4_click();
        fail("Expecting exception: SutCommunicationException");
      } catch(SutCommunicationException e) {
        /*
         * java.lang.RuntimeException: removeCartButton can't be invoked
         */
      }
  }

  //Test case number: 111
  /*
   * 6 covered goals:
   * 1 v2.TestFlex.IDY_cancas_1_click()V: I9 Branch 310 IF_ICMPEQ L6458 - true
   * 2 v2.TestFlex.IDY_cancas_1_click()V: I27 Branch 312 IFNE L6462 - true
   * 3 v2.TestFlex.IDY_cancas_1_click()V: I142 Branch 313 TABLESWITCH L6494 Case 1 - false
   * 4 v2.TestFlex.IDY_cancas_1_click()V: I142 Branch 314 TABLESWITCH L6494 Case 2 - true
   * 5 v2.TestFlex.IDY_cancas_1_click()V: I142 Branch 315 TABLESWITCH L6494 Default-Case - false
   * 6 v2.TestFlex.IDY_cancas_1_click()V: I146 Branch 316 IFNE L6516 - false
   */  @Test
  public void test111()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_cancas_1_click();
  }

  //Test case number: 112
  /*
   * 3 covered goals:
   * 1 v2.TestFlex.IDY_cancas_1_click()V: I9 Branch 310 IF_ICMPEQ L6458 - false
   * 2 v2.TestFlex.IDY_cancas_1_click()V: I14 Branch 311 IF_ICMPEQ L6459 - false
   * 3 v2.TestFlex.IDY_cancas_1_click()V: I27 Branch 312 IFNE L6462 - false
   */  @Test
  public void test112()  throws Throwable  {
      try {
        TestFlex.IDY_cancas_1_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_cancas_1_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 113
  /*
   * 4 covered goals:
   * 1 v2.TestFlex.IDY_cancas_1_click()V: I14 Branch 311 IF_ICMPEQ L6459 - true
   * 2 v2.TestFlex.IDY_cancas_1_click()V: I142 Branch 313 TABLESWITCH L6494 Case 1 - true
   * 3 v2.TestFlex.IDY_cancas_1_click()V: I142 Branch 314 TABLESWITCH L6494 Case 2 - false
   * 4 v2.TestFlex.IDY_cancas_1_click()V: I206 Branch 317 IFLE L6583 - false
   */  @Test
  public void test113()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_cancas_4_click();
      TestFlex.IDY_purchase_this_click();
      TestFlex.IDY_cancas_1_click();
  }

  //Test case number: 114
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_quantity_4_click()V: I9 Branch 318 IF_ICMPNE L6624 - true
   * 2 v2.TestFlex.IDY_quantity_4_click()V: I20 Branch 319 IFNE L6627 - false
   */  @Test
  public void test114()  throws Throwable  {
      try {
        TestFlex.IDY_quantity_4_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_quantity_4_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 115
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_quantity_4_click()V: I9 Branch 318 IF_ICMPNE L6624 - false
   * 2 v2.TestFlex.IDY_quantity_4_click()V: I20 Branch 319 IFNE L6627 - true
   * 3 v2.TestFlex.IDY_quantity_4_click()V: I135 Branch 320 TABLESWITCH L6659 Case 1 - true
   * 4 v2.TestFlex.IDY_quantity_4_click()V: I135 Branch 321 TABLESWITCH L6659 Default-Case - false
   * 5 v2.TestFlex.IDY_quantity_4_click()V: I139 Branch 322 IFLE L6682 - false
   */  @Test
  public void test115()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_quantity_4_click();
  }

  //Test case number: 116
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_quantity_4_type(I)V: I17 Branch 323 IF_ICMPNE L6733 - true
   * 2 v2.TestFlex.IDY_quantity_4_type(I)V: I28 Branch 324 IFNE L6736 - false
   */  @Test
  public void test116()  throws Throwable  {
      int int0 = 600;
      try {
        TestFlex.IDY_quantity_4_type(int0);
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_quantity_4_type doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 117
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_quantity_4_type(I)V: I17 Branch 323 IF_ICMPNE L6733 - false
   * 2 v2.TestFlex.IDY_quantity_4_type(I)V: I28 Branch 324 IFNE L6736 - true
   */  @Test
  public void test117()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_6_click();
      try {
        TestFlex.IDY_quantity_4_type(int0);
        fail("Expecting exception: SutCommunicationException");
      } catch(SutCommunicationException e) {
        /*
         * java.lang.RuntimeException: can't change a cart item if the item is not there
         */
      }
  }

  //Test case number: 118
  /*
   * 3 covered goals:
   * 1 v2.TestFlex.IDY_quantity_4_type(I)V: I144 Branch 325 TABLESWITCH L6768 Case 1 - true
   * 2 v2.TestFlex.IDY_quantity_4_type(I)V: I144 Branch 326 TABLESWITCH L6768 Default-Case - false
   * 3 v2.TestFlex.IDY_quantity_4_type(I)V: I148 Branch 327 IFLE L6792 - false
   */  @Test
  public void test118()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_6_click();
      TestFlex.IDY_purchase_4_click();
      TestFlex.IDY_quantity_4_type(int0);
  }

  //Test case number: 119
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_addressState_change(I)V: I17 Branch 328 IF_ICMPNE L6842 - true
   * 2 v2.TestFlex.IDY_addressState_change(I)V: I28 Branch 329 IFNE L6845 - false
   */  @Test
  public void test119()  throws Throwable  {
      int int0 = 850;
      try {
        TestFlex.IDY_addressState_change(int0);
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_addressState_change doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 120
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_addressState_change(I)V: I17 Branch 328 IF_ICMPNE L6842 - false
   * 2 v2.TestFlex.IDY_addressState_change(I)V: I28 Branch 329 IFNE L6845 - true
   */  @Test
  public void test120()  throws Throwable  {
      TestFlex.image0_click();
      int int0 = 9;
      try {
        TestFlex.IDY_addressState_change(int0);
        fail("Expecting exception: SutCommunicationException");
      } catch(SutCommunicationException e) {
        /*
         * java.lang.RuntimeException: button not visible
         */
      }
  }

  //Test case number: 121
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_details_1_click()V: I9 Branch 333 IF_ICMPNE L6950 - true
   * 2 v2.TestFlex.IDY_details_1_click()V: I20 Branch 334 IFNE L6953 - false
   */  @Test
  public void test121()  throws Throwable  {
      try {
        TestFlex.IDY_details_1_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_details_1_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 122
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_details_1_click()V: I9 Branch 333 IF_ICMPNE L6950 - false
   * 2 v2.TestFlex.IDY_details_1_click()V: I20 Branch 334 IFNE L6953 - true
   * 3 v2.TestFlex.IDY_details_1_click()V: I135 Branch 335 TABLESWITCH L6985 Case 1 - true
   * 4 v2.TestFlex.IDY_details_1_click()V: I135 Branch 336 TABLESWITCH L6985 Default-Case - false
   * 5 v2.TestFlex.IDY_details_1_click()V: I139 Branch 337 IFLE L7019 - false
   */  @Test
  public void test122()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_details_1_click();
  }

  //Test case number: 123
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_remove_shoppingCart_9_click()V: I9 Branch 338 IF_ICMPNE L7059 - true
   * 2 v2.TestFlex.IDY_remove_shoppingCart_9_click()V: I20 Branch 339 IFNE L7062 - false
   */  @Test
  public void test123()  throws Throwable  {
      try {
        TestFlex.IDY_remove_shoppingCart_9_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_remove_shoppingCart_9_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 124
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_remove_shoppingCart_9_click()V: I9 Branch 338 IF_ICMPNE L7059 - false
   * 2 v2.TestFlex.IDY_remove_shoppingCart_9_click()V: I20 Branch 339 IFNE L7062 - true
   */  @Test
  public void test124()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_cancas_4_click();
      TestFlex.IDY_purchase_this_click();
      try {
        TestFlex.IDY_remove_shoppingCart_9_click();
        fail("Expecting exception: SutCommunicationException");
      } catch(SutCommunicationException e) {
        /*
         * java.lang.RuntimeException: removeCartButton can't be invoked
         */
      }
  }

  //Test case number: 125
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_purchase_15_click()V: I9 Branch 343 IF_ICMPNE L7168 - true
   * 2 v2.TestFlex.IDY_purchase_15_click()V: I20 Branch 344 IFNE L7171 - false
   */  @Test
  public void test125()  throws Throwable  {
      try {
        TestFlex.IDY_purchase_15_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_purchase_15_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 126
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_img_14_click()V: I9 Branch 348 IF_ICMPNE L7276 - true
   * 2 v2.TestFlex.IDY_img_14_click()V: I20 Branch 349 IFNE L7279 - false
   */  @Test
  public void test126()  throws Throwable  {
      try {
        TestFlex.IDY_img_14_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_img_14_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 127
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_img_14_click()V: I9 Branch 348 IF_ICMPNE L7276 - false
   * 2 v2.TestFlex.IDY_img_14_click()V: I20 Branch 349 IFNE L7279 - true
   * 3 v2.TestFlex.IDY_img_14_click()V: I135 Branch 350 TABLESWITCH L7311 Case 1 - true
   * 4 v2.TestFlex.IDY_img_14_click()V: I135 Branch 351 TABLESWITCH L7311 Default-Case - false
   * 5 v2.TestFlex.IDY_img_14_click()V: I139 Branch 352 IFLE L7352 - false
   */  @Test
  public void test127()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_img_14_click();
  }

  //Test case number: 128
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_cancas_14_click()V: I9 Branch 353 IF_ICMPNE L7385 - true
   * 2 v2.TestFlex.IDY_cancas_14_click()V: I20 Branch 354 IFNE L7388 - false
   */  @Test
  public void test128()  throws Throwable  {
      try {
        TestFlex.IDY_cancas_14_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_cancas_14_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 129
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_cancas_14_click()V: I9 Branch 353 IF_ICMPNE L7385 - false
   * 2 v2.TestFlex.IDY_cancas_14_click()V: I20 Branch 354 IFNE L7388 - true
   * 3 v2.TestFlex.IDY_cancas_14_click()V: I135 Branch 355 TABLESWITCH L7420 Case 1 - true
   * 4 v2.TestFlex.IDY_cancas_14_click()V: I135 Branch 356 TABLESWITCH L7420 Default-Case - false
   * 5 v2.TestFlex.IDY_cancas_14_click()V: I139 Branch 357 IFLE L7462 - false
   */  @Test
  public void test129()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_cancas_14_click();
  }

  //Test case number: 130
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_myphonenr3_click()V: I9 Branch 358 IF_ICMPNE L7494 - true
   * 2 v2.TestFlex.IDY_myphonenr3_click()V: I20 Branch 359 IFNE L7497 - false
   */  @Test
  public void test130()  throws Throwable  {
      try {
        TestFlex.IDY_myphonenr3_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_myphonenr3_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 131
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_myphonenr3_click()V: I9 Branch 358 IF_ICMPNE L7494 - false
   * 2 v2.TestFlex.IDY_myphonenr3_click()V: I20 Branch 359 IFNE L7497 - true
   * 3 v2.TestFlex.IDY_myphonenr3_click()V: I135 Branch 360 TABLESWITCH L7529 Case 2 - true
   * 4 v2.TestFlex.IDY_myphonenr3_click()V: I135 Branch 361 TABLESWITCH L7529 Default-Case - false
   * 5 v2.TestFlex.IDY_myphonenr3_click()V: I139 Branch 362 IFNE L7533 - false
   */  @Test
  public void test131()  throws Throwable  {
      TestFlex.IDY_myphonenr2_click();
      TestFlex.IDY_myphonenr3_click();
  }

  //Test case number: 132
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_purchase_2_click()V: I9 Branch 363 IF_ICMPNE L7602 - true
   * 2 v2.TestFlex.IDY_purchase_2_click()V: I20 Branch 364 IFNE L7605 - false
   */  @Test
  public void test132()  throws Throwable  {
      try {
        TestFlex.IDY_purchase_2_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_purchase_2_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 133
  /*
   * 4 covered goals:
   * 1 v2.TestFlex.IDY_searchproduct_click()V: I9 Branch 368 IF_ICMPEQ L7711 - true
   * 2 v2.TestFlex.IDY_searchproduct_click()V: I141 Branch 371 TABLESWITCH L7747 Case 0 - false
   * 3 v2.TestFlex.IDY_searchproduct_click()V: I141 Branch 373 TABLESWITCH L7747 Case 2 - true
   * 4 v2.TestFlex.IDY_searchproduct_click()V: I145 Branch 375 IFNE L7761 - false
   */  @Test
  public void test133()  throws Throwable  {
      TestFlex.IDY_myphonenr1_click();
      TestFlex.IDY_searchproduct_click();
  }

  //Test case number: 134
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_searchproduct_click()V: I13 Branch 369 IFEQ L7712 - false
   * 2 v2.TestFlex.IDY_searchproduct_click()V: I26 Branch 370 IFNE L7715 - false
   */  @Test
  public void test134()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      try {
        TestFlex.IDY_searchproduct_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_searchproduct_click doesn't apply to current state:n4
         */
      }
  }

  //Test case number: 135
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_buttonSearch_click()V: I9 Branch 377 IF_ICMPNE L7841 - true
   * 2 v2.TestFlex.IDY_buttonSearch_click()V: I20 Branch 378 IFNE L7844 - false
   */  @Test
  public void test135()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      try {
        TestFlex.IDY_buttonSearch_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_buttonSearch_click doesn't apply to current state:n4
         */
      }
  }

  //Test case number: 136
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_buttonSearch_click()V: I9 Branch 377 IF_ICMPNE L7841 - false
   * 2 v2.TestFlex.IDY_buttonSearch_click()V: I20 Branch 378 IFNE L7844 - true
   * 3 v2.TestFlex.IDY_buttonSearch_click()V: I135 Branch 379 TABLESWITCH L7876 Case 2 - true
   * 4 v2.TestFlex.IDY_buttonSearch_click()V: I135 Branch 380 TABLESWITCH L7876 Default-Case - false
   * 5 v2.TestFlex.IDY_buttonSearch_click()V: I139 Branch 381 IFNE L7887 - false
   */  @Test
  public void test136()  throws Throwable  {
      TestFlex.IDY_myphonenr2_click();
      TestFlex.IDY_buttonSearch_click();
  }

  //Test case number: 137
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_cancas_9_click()V: I9 Branch 382 IF_ICMPNE L7949 - true
   * 2 v2.TestFlex.IDY_cancas_9_click()V: I20 Branch 383 IFNE L7952 - false
   */  @Test
  public void test137()  throws Throwable  {
      try {
        TestFlex.IDY_cancas_9_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_cancas_9_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 138
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_cancas_9_click()V: I9 Branch 382 IF_ICMPNE L7949 - false
   * 2 v2.TestFlex.IDY_cancas_9_click()V: I20 Branch 383 IFNE L7952 - true
   * 3 v2.TestFlex.IDY_cancas_9_click()V: I135 Branch 384 TABLESWITCH L7984 Case 1 - true
   * 4 v2.TestFlex.IDY_cancas_9_click()V: I135 Branch 385 TABLESWITCH L7984 Default-Case - false
   * 5 v2.TestFlex.IDY_cancas_9_click()V: I139 Branch 386 IFLE L8010 - false
   */  @Test
  public void test138()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_cancas_9_click();
  }

  //Test case number: 139
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_img_4_click()V: I9 Branch 387 IF_ICMPNE L8058 - true
   * 2 v2.TestFlex.IDY_img_4_click()V: I20 Branch 388 IFNE L8061 - false
   */  @Test
  public void test139()  throws Throwable  {
      try {
        TestFlex.IDY_img_4_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_img_4_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 140
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_img_4_click()V: I9 Branch 387 IF_ICMPNE L8058 - false
   * 2 v2.TestFlex.IDY_img_4_click()V: I20 Branch 388 IFNE L8061 - true
   * 3 v2.TestFlex.IDY_img_4_click()V: I135 Branch 389 TABLESWITCH L8093 Case 2 - true
   * 4 v2.TestFlex.IDY_img_4_click()V: I135 Branch 390 TABLESWITCH L8093 Default-Case - false
   * 5 v2.TestFlex.IDY_img_4_click()V: I139 Branch 391 IFNE L8119 - false
   */  @Test
  public void test140()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_img_4_click();
  }

  //Test case number: 141
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_cancas_3_click()V: I9 Branch 392 IF_ICMPNE L8166 - true
   * 2 v2.TestFlex.IDY_cancas_3_click()V: I20 Branch 393 IFNE L8169 - false
   */  @Test
  public void test141()  throws Throwable  {
      try {
        TestFlex.IDY_cancas_3_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_cancas_3_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 142
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_cancas_3_click()V: I9 Branch 392 IF_ICMPNE L8166 - false
   * 2 v2.TestFlex.IDY_cancas_3_click()V: I20 Branch 393 IFNE L8169 - true
   * 3 v2.TestFlex.IDY_cancas_3_click()V: I135 Branch 394 TABLESWITCH L8201 Case 1 - true
   * 4 v2.TestFlex.IDY_cancas_3_click()V: I135 Branch 395 TABLESWITCH L8201 Default-Case - false
   * 5 v2.TestFlex.IDY_cancas_3_click()V: I139 Branch 396 IFLE L8219 - false
   */  @Test
  public void test142()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_cancas_3_click();
  }

  //Test case number: 143
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.TabNavigator0_change(I)V: I17 Branch 397 IF_ICMPNE L8275 - true
   * 2 v2.TestFlex.TabNavigator0_change(I)V: I28 Branch 398 IFNE L8278 - false
   */  @Test
  public void test143()  throws Throwable  {
      int int0 = (-26);
      try {
        TestFlex.TabNavigator0_change(int0);
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * TabNavigator0_change doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 144
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.TabNavigator0_change(I)V: I17 Branch 397 IF_ICMPNE L8275 - false
   * 2 v2.TestFlex.TabNavigator0_change(I)V: I28 Branch 398 IFNE L8278 - true
   */  @Test
  public void test144()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      try {
        TestFlex.TabNavigator0_change(int0);
        fail("Expecting exception: SutCommunicationException");
      } catch(SutCommunicationException e) {
        /*
         * java.lang.RuntimeException: button not visible
         */
      }
  }

  //Test case number: 145
  /*
   * 3 covered goals:
   * 1 v2.TestFlex.TabNavigator0_change(I)V: I144 Branch 399 TABLESWITCH L8310 Case 2 - true
   * 2 v2.TestFlex.TabNavigator0_change(I)V: I144 Branch 400 TABLESWITCH L8310 Default-Case - false
   * 3 v2.TestFlex.TabNavigator0_change(I)V: I148 Branch 401 IFNE L8338 - false
   */  @Test
  public void test145()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_labelPrice_15_click();
      TestFlex.TabNavigator0_change(int0);
  }

  //Test case number: 146
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_cancas_6_click()V: I9 Branch 402 IF_ICMPNE L8383 - true
   * 2 v2.TestFlex.IDY_cancas_6_click()V: I20 Branch 403 IFNE L8386 - false
   */  @Test
  public void test146()  throws Throwable  {
      try {
        TestFlex.IDY_cancas_6_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_cancas_6_click doesn't apply to current state:n1
         */
      }
  }

  //Test case number: 147
  /*
   * 5 covered goals:
   * 1 v2.TestFlex.IDY_cancas_6_click()V: I9 Branch 402 IF_ICMPNE L8383 - false
   * 2 v2.TestFlex.IDY_cancas_6_click()V: I20 Branch 403 IFNE L8386 - true
   * 3 v2.TestFlex.IDY_cancas_6_click()V: I135 Branch 404 TABLESWITCH L8418 Case 1 - true
   * 4 v2.TestFlex.IDY_cancas_6_click()V: I135 Branch 405 TABLESWITCH L8418 Default-Case - false
   * 5 v2.TestFlex.IDY_cancas_6_click()V: I139 Branch 406 IFLE L8421 - false
   */  @Test
  public void test147()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_cancas_6_click();
  }
}
