//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.11 at 09:58:02 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://fittest.eu/eventabstraction", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.fittest.eventabstraction;
