//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 12:51:31 PM CET 
//


package eu.fittest.project.config;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BrowserType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BrowserType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HtmlUnitDriver"/>
 *     &lt;enumeration value="FirefoxDriver"/>
 *     &lt;enumeration value="ChromeDriver"/>
 *     &lt;enumeration value="InternetExplorerDriver"/>
 *     &lt;enumeration value="FlexObjectDriver"/>
 *     &lt;enumeration value="FlashApplication"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BrowserType")
@XmlEnum
public enum BrowserType {

    @XmlEnumValue("HtmlUnitDriver")
    HTML_UNIT_DRIVER("HtmlUnitDriver"),
    @XmlEnumValue("FirefoxDriver")
    FIREFOX_DRIVER("FirefoxDriver"),
    @XmlEnumValue("ChromeDriver")
    CHROME_DRIVER("ChromeDriver"),
    @XmlEnumValue("InternetExplorerDriver")
    INTERNET_EXPLORER_DRIVER("InternetExplorerDriver"),
    @XmlEnumValue("FlexObjectDriver")
    FLEX_OBJECT_DRIVER("FlexObjectDriver"),
    @XmlEnumValue("FlashApplication")
    FLASH_APPLICATION("FlashApplication");
    private final String value;

    BrowserType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BrowserType fromValue(String v) {
        for (BrowserType c: BrowserType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
