//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 12:51:31 PM CET 
//


package eu.fittest.project.config;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InferenceTechniqueType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="InferenceTechniqueType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SEQUENCE-BASED"/>
 *     &lt;enumeration value="STATE-BASED"/>
 *     &lt;enumeration value="AUTO-ABS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "InferenceTechniqueType")
@XmlEnum
public enum InferenceTechniqueType {

    @XmlEnumValue("SEQUENCE-BASED")
    SEQUENCE_BASED("SEQUENCE-BASED"),
    @XmlEnumValue("STATE-BASED")
    STATE_BASED("STATE-BASED"),
    @XmlEnumValue("AUTO-ABS")
    AUTO_ABS("AUTO-ABS");
    private final String value;

    InferenceTechniqueType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InferenceTechniqueType fromValue(String v) {
        for (InferenceTechniqueType c: InferenceTechniqueType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
