//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 12:51:31 PM CET 
//


package eu.fittest.project.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ModelInferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModelInferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="domainInputSpecFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="absFuncDefFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modelFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="inferenceTechnique" type="{http://www.fittest.eu/TestProject}InferenceTechniqueType"/>
 *         &lt;element name="generateDot" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="gaParam" type="{http://www.fittest.eu/TestProject}GAParameterType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModelInferenceType", propOrder = {
    "domainInputSpecFile",
    "absFuncDefFile",
    "modelFile",
    "inferenceTechnique",
    "generateDot",
    "gaParam"
})
public class ModelInferenceType {

    @XmlElement(required = true)
    protected String domainInputSpecFile;
    @XmlElement(required = true)
    protected String absFuncDefFile;
    @XmlElement(required = true)
    protected String modelFile;
    @XmlElement(required = true)
    protected InferenceTechniqueType inferenceTechnique;
    protected boolean generateDot;
    @XmlElement(required = true)
    protected GAParameterType gaParam;

    /**
     * Gets the value of the domainInputSpecFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomainInputSpecFile() {
        return domainInputSpecFile;
    }

    /**
     * Sets the value of the domainInputSpecFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomainInputSpecFile(String value) {
        this.domainInputSpecFile = value;
    }

    /**
     * Gets the value of the absFuncDefFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbsFuncDefFile() {
        return absFuncDefFile;
    }

    /**
     * Sets the value of the absFuncDefFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbsFuncDefFile(String value) {
        this.absFuncDefFile = value;
    }

    /**
     * Gets the value of the modelFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelFile() {
        return modelFile;
    }

    /**
     * Sets the value of the modelFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelFile(String value) {
        this.modelFile = value;
    }

    /**
     * Gets the value of the inferenceTechnique property.
     * 
     * @return
     *     possible object is
     *     {@link InferenceTechniqueType }
     *     
     */
    public InferenceTechniqueType getInferenceTechnique() {
        return inferenceTechnique;
    }

    /**
     * Sets the value of the inferenceTechnique property.
     * 
     * @param value
     *     allowed object is
     *     {@link InferenceTechniqueType }
     *     
     */
    public void setInferenceTechnique(InferenceTechniqueType value) {
        this.inferenceTechnique = value;
    }

    /**
     * Gets the value of the generateDot property.
     * 
     */
    public boolean isGenerateDot() {
        return generateDot;
    }

    /**
     * Sets the value of the generateDot property.
     * 
     */
    public void setGenerateDot(boolean value) {
        this.generateDot = value;
    }

    /**
     * Gets the value of the gaParam property.
     * 
     * @return
     *     possible object is
     *     {@link GAParameterType }
     *     
     */
    public GAParameterType getGaParam() {
        return gaParam;
    }

    /**
     * Sets the value of the gaParam property.
     * 
     * @param value
     *     allowed object is
     *     {@link GAParameterType }
     *     
     */
    public void setGaParam(GAParameterType value) {
        this.gaParam = value;
    }

}
