//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 12:51:31 PM CET 
//


package eu.fittest.project.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OracleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OracleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GHCRTopts" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="oracleFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reportFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="eventsToInclude" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fieldsToInclude" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="functionsToInclude" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lloOption" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="violationFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OracleType", propOrder = {
    "ghcrTopts",
    "oracleFile",
    "reportFile",
    "eventsToInclude",
    "fieldsToInclude",
    "functionsToInclude",
    "lloOption",
    "violationFile"
})
public class OracleType {

    @XmlElement(name = "GHCRTopts", required = true)
    protected String ghcrTopts;
    @XmlElement(required = true, defaultValue = "oracle.inv")
    protected String oracleFile;
    @XmlElement(required = true, defaultValue = "report.txt")
    protected String reportFile;
    @XmlElement(required = true)
    protected String eventsToInclude;
    @XmlElement(required = true)
    protected String fieldsToInclude;
    @XmlElement(required = true)
    protected String functionsToInclude;
    @XmlElement(required = true)
    protected String lloOption;
    @XmlElement(required = true, defaultValue = "violations.txt")
    protected String violationFile;

    /**
     * Gets the value of the ghcrTopts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGHCRTopts() {
        return ghcrTopts;
    }

    /**
     * Sets the value of the ghcrTopts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGHCRTopts(String value) {
        this.ghcrTopts = value;
    }

    /**
     * Gets the value of the oracleFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOracleFile() {
        return oracleFile;
    }

    /**
     * Sets the value of the oracleFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOracleFile(String value) {
        this.oracleFile = value;
    }

    /**
     * Gets the value of the reportFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportFile() {
        return reportFile;
    }

    /**
     * Sets the value of the reportFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportFile(String value) {
        this.reportFile = value;
    }

    /**
     * Gets the value of the eventsToInclude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventsToInclude() {
        return eventsToInclude;
    }

    /**
     * Sets the value of the eventsToInclude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventsToInclude(String value) {
        this.eventsToInclude = value;
    }

    /**
     * Gets the value of the fieldsToInclude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldsToInclude() {
        return fieldsToInclude;
    }

    /**
     * Sets the value of the fieldsToInclude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldsToInclude(String value) {
        this.fieldsToInclude = value;
    }

    /**
     * Gets the value of the functionsToInclude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunctionsToInclude() {
        return functionsToInclude;
    }

    /**
     * Sets the value of the functionsToInclude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunctionsToInclude(String value) {
        this.functionsToInclude = value;
    }

    /**
     * Gets the value of the lloOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLloOption() {
        return lloOption;
    }

    /**
     * Sets the value of the lloOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLloOption(String value) {
        this.lloOption = value;
    }

    /**
     * Gets the value of the violationFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViolationFile() {
        return violationFile;
    }

    /**
     * Sets the value of the violationFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViolationFile(String value) {
        this.violationFile = value;
    }

}
