[clickvideo_true(p)] ~ [] (1,0) Skip
[clickcamera_true(p)] ~ [] (1,0) Skip
[clickcamera_false(p)] ~ [] (1,0) Skip
[clickfind_phones(p)] ~ [] (2,0) Skip
[clickview_cart(p)] ~ [] (5,0) Skip
[clicktriband_true(p)] ~ [] (2,0) Skip
[clicktriband_false(p)] ~ [] (2,0) Skip
[clickvideo_false(p)] ~ [] (1,0) Skip
[clickOK(p)] ~ [] (1,0) Skip
[clickcompare_button_showingThumbnails(p)] ~ [] (3,0) Skip
[itemclickButtonBar(p)] ~ [] (9,0) Skip
[clickvideo_true(p)] ~ [] (3,0) Skip
[clickcamera_true(p)] ~ [] (3,0) Skip
[clickcamera_false(p)] ~ [] (3,0) Skip
[clickfind_phones(p)] ~ [] (6,0) Skip
[clickview_cart(p)] ~ [] (15,0) Skip
[clicktriband_true(p)] ~ [] (6,0) Skip
[clicktriband_false(p)] ~ [] (6,0) Skip
[clickvideo_false(p)] ~ [] (3,0) Skip
[clickOK(p)] ~ [] (3,0) Skip
[clickcompare_button_showingThumbnails(p)] ~ [] (9,0) Skip
[itemclickButtonBar(p)] ~ [] (27,0) Skip
