//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 12:50:35 PM CET 
//


package eu.fittest.phplog;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for request complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="request">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="method" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="querystring" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="headers" type="{http://fittest.eu/phplog}headers"/>
 *         &lt;element name="get" type="{http://fittest.eu/phplog}arrayValue"/>
 *         &lt;element name="post" type="{http://fittest.eu/phplog}arrayValue"/>
 *         &lt;element name="cookie" type="{http://fittest.eu/phplog}arrayValue"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "request", propOrder = {
    "method",
    "uri",
    "querystring",
    "headers",
    "get",
    "post",
    "cookie"
})
public class Request {

    @XmlElement(required = true)
    protected String method;
    @XmlElement(required = true)
    protected String uri;
    @XmlElement(required = true)
    protected String querystring;
    @XmlElement(required = true)
    protected Headers headers;
    @XmlElement(required = true)
    protected ArrayValue get;
    @XmlElement(required = true)
    protected ArrayValue post;
    @XmlElement(required = true)
    protected ArrayValue cookie;

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethod(String value) {
        this.method = value;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUri(String value) {
        this.uri = value;
    }

    /**
     * Gets the value of the querystring property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuerystring() {
        return querystring;
    }

    /**
     * Sets the value of the querystring property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuerystring(String value) {
        this.querystring = value;
    }

    /**
     * Gets the value of the headers property.
     * 
     * @return
     *     possible object is
     *     {@link Headers }
     *     
     */
    public Headers getHeaders() {
        return headers;
    }

    /**
     * Sets the value of the headers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Headers }
     *     
     */
    public void setHeaders(Headers value) {
        this.headers = value;
    }

    /**
     * Gets the value of the get property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayValue }
     *     
     */
    public ArrayValue getGet() {
        return get;
    }

    /**
     * Sets the value of the get property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayValue }
     *     
     */
    public void setGet(ArrayValue value) {
        this.get = value;
    }

    /**
     * Gets the value of the post property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayValue }
     *     
     */
    public ArrayValue getPost() {
        return post;
    }

    /**
     * Sets the value of the post property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayValue }
     *     
     */
    public void setPost(ArrayValue value) {
        this.post = value;
    }

    /**
     * Gets the value of the cookie property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayValue }
     *     
     */
    public ArrayValue getCookie() {
        return cookie;
    }

    /**
     * Sets the value of the cookie property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayValue }
     *     
     */
    public void setCookie(ArrayValue value) {
        this.cookie = value;
    }

}
