//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 12:50:35 PM CET 
//


package eu.fittest.phplog;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for value complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="value">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bool" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="int" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="float" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="array" type="{http://fittest.eu/phplog}arrayValue"/>
 *         &lt;element name="object" type="{http://fittest.eu/phplog}objectValue"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "value", propOrder = {
    "value"
})
@XmlSeeAlso({
    Entry.class,
    Property.class
})
public class Value {

    @XmlElements({
        @XmlElement(name = "int", type = Integer.class),
        @XmlElement(name = "bool", type = Boolean.class),
        @XmlElement(name = "string", type = String.class),
        @XmlElement(name = "object", type = ObjectValue.class),
        @XmlElement(name = "float", type = Float.class),
        @XmlElement(name = "array", type = ArrayValue.class)
    })
    protected Object value;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     {@link Boolean }
     *     {@link String }
     *     {@link ObjectValue }
     *     {@link Float }
     *     {@link ArrayValue }
     *     
     */
    public Object getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     {@link Boolean }
     *     {@link String }
     *     {@link ObjectValue }
     *     {@link Float }
     *     {@link ArrayValue }
     *     
     */
    public void setValue(Object value) {
        this.value = value;
    }

}
