/*
 * This file was automatically generated by EvoSuite
 */

package v2;

import org.junit.Test;
import static org.junit.Assert.*;
import eu.fittest.fbk.efsm2ct.efsm2mon.runtime.FsmtesterException;
import eu.fittest.fbk.efsm2ct.efsm2mon.runtime.NotApplicableException;
import eu.fittest.fbk.efsm2ct.efsm2mon.runtime.SutCommunicationException;
import eu.fittest.fbk.efsm2ct.efsm2mon.runtime.UnderSpecifiedException;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import v2.TestFlex;

public class A {

  
  //Test case number: 3
  /*
   * 19 covered goals:
   * 1 v2.TestFlex.IDY_cancas_13_click()V: I9 Branch 9 IF_ICMPNE L211 - false
   * 2 v2.TestFlex.IDY_cancas_13_click()V: I20 Branch 10 IFNE L214 - true
   * 3 v2.TestFlex.IDY_cancas_13_click()V: I135 Branch 11 TABLESWITCH L246 Case 1 - true
   * 4 v2.TestFlex.IDY_cancas_13_click()V: I135 Branch 12 TABLESWITCH L246 Default-Case - false
   * 5 v2.TestFlex.IDY_cancas_13_click()V: I139 Branch 13 IFLE L285 - false
   * 6 v2.TestFlex.IDY_purchase_1_click()V: I9 Branch 250 IF_ICMPEQ L5229 - true
   * 7 v2.TestFlex.IDY_purchase_1_click()V: I27 Branch 252 IFNE L5233 - true
   * 8 v2.TestFlex.IDY_purchase_1_click()V: I142 Branch 253 TABLESWITCH L5265 Case 1 - false
   * 9 v2.TestFlex.IDY_purchase_1_click()V: I142 Branch 254 TABLESWITCH L5265 Case 2 - true
   * 10 v2.TestFlex.IDY_purchase_1_click()V: I142 Branch 255 TABLESWITCH L5265 Default-Case - false
   * 11 v2.TestFlex.IDY_purchase_1_click()V: I146 Branch 256 IFLE L5290 - false
   * 12 v2.TestFlex.ButtonBar0_itemclick(I)V: I17 Branch 294 IF_ICMPEQ L6161 - false
   * 13 v2.TestFlex.ButtonBar0_itemclick(I)V: I21 Branch 295 IFEQ L6162 - true
   * 14 v2.TestFlex.ButtonBar0_itemclick(I)V: I39 Branch 297 IFNE L6166 - true
   * 15 v2.TestFlex.ButtonBar0_itemclick(I)V: I155 Branch 298 TABLESWITCH L6198 Case 0 - true
   * 16 v2.TestFlex.ButtonBar0_itemclick(I)V: I155 Branch 299 TABLESWITCH L6198 Case 1 - false
   * 17 v2.TestFlex.ButtonBar0_itemclick(I)V: I155 Branch 300 TABLESWITCH L6198 Case 2 - false
   * 18 v2.TestFlex.ButtonBar0_itemclick(I)V: I155 Branch 301 TABLESWITCH L6198 Default-Case - false
   * 19 v2.TestFlex.ButtonBar0_itemclick(I)V: I219 Branch 303 IFNE L6258 - false
   */  @Test
  public void test3()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      TestFlex.IDY_cancas_13_click();
  }

  //Test case number: 60
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.Image6_click()V: I9 Branch 153 IF_ICMPNE L3311 - false
   * 2 v2.TestFlex.Image6_click()V: I20 Branch 154 IFNE L3314 - true
   */  @Test
  public void test60()  throws Throwable  {
      int int0 = 1;
      TestFlex.ButtonBar0_itemclick(int0);
      TestFlex.IDY_purchase_1_click();
      try {
        TestFlex.Image6_click();
        fail("Expecting exception: SutCommunicationException");
      } catch(SutCommunicationException e) {
        /*
         * java.lang.RuntimeException: button not visible
         */
      }
  }

  //Test case number: 61
  /*
   * 2 covered goals:
   * 1 v2.TestFlex.IDY_cancas_2_click()V: I9 Branch 158 IF_ICMPNE L3420 - true
   * 2 v2.TestFlex.IDY_cancas_2_click()V: I20 Branch 159 IFNE L3423 - false
   */  @Test
  public void test61()  throws Throwable  {
      try {
        TestFlex.IDY_cancas_2_click();
        fail("Expecting exception: NotApplicableException");
      } catch(NotApplicableException e) {
        /*
         * IDY_cancas_2_click doesn't apply to current state:n1
         */
      }
  }

  
}
