/**
 *
 * $Id$
 */
package eu.fittest.test.project.validation;

import eu.fittest.test.project.SUTTechnologyType;

/**
 * A sample validator interface for {@link eu.fittest.test.project.GeneralType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GeneralTypeValidator {
	boolean validate();

	boolean validateType(SUTTechnologyType value);
	boolean validateBaseURL(String value);
	boolean validateEntryPage(String value);
	boolean validateServerFolder(String value);
}
