/**
 *
 * $Id$
 */
package eu.fittest.test.project.validation;

import eu.fittest.test.project.InstrumentationType;
import eu.fittest.test.project.LogTargetType;

/**
 * A sample validator interface for {@link eu.fittest.test.project.LoggingType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LoggingTypeValidator {
	boolean validate();

	boolean validateInstrumentation(InstrumentationType value);
	boolean validateLogTarget(LogTargetType value);
}
