/**
 *
 * $Id$
 */
package eu.fittest.test.project.validation;

import eu.fittest.test.project.GAParameterType;
import eu.fittest.test.project.InferenceTechniqueType;

/**
 * A sample validator interface for {@link eu.fittest.test.project.ModelInferenceType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModelInferenceTypeValidator {
	boolean validate();

	boolean validateDomainInputSpecFile(String value);
	boolean validateAbsFuncDefFile(String value);
	boolean validateModelFile(String value);
	boolean validateInferenceTechnique(InferenceTechniqueType value);
	boolean validateGenerateDot(boolean value);

	boolean validateGaParam(GAParameterType value);
}
