/**
 *
 * $Id$
 */
package eu.fittest.test.project.validation;

import eu.fittest.test.project.GeneralType;
import eu.fittest.test.project.LoggingType;
import eu.fittest.test.project.ModelInferenceType;
import eu.fittest.test.project.OracleType;
import eu.fittest.test.project.TestGenerationType;

/**
 * A sample validator interface for {@link eu.fittest.test.project.TestProject}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TestProjectValidator {
	boolean validate();

	boolean validateGeneral(GeneralType value);
	boolean validateLogging(LoggingType value);
	boolean validateModelInference(ModelInferenceType value);
	boolean validateTestGeneration(TestGenerationType value);
	boolean validateOracle(OracleType value);
}
