//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.20 at 02:50:18 PM CET 
//


package eu.fbk.se.fsm.cte;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.fbk.se.fsm.cte package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.fbk.se.fsm.cte
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link M return new Marks();
    }

    /**
     * Create an instance of {@link TestSequence.TestStep }
     * 
     */
    public TestSequence.TestStep createTestSequteObject createCteObject() {
        return new CteObject();
    }

    /**
     * Create an instance of {@link TestSequence }
     * 
     */
    public TestSequence createTestSequence() {
        return new TestSequence();
    }

    /**
     * Create an instance of {@link ClassificatiTestStep() {
        return new TestSequence.TestStep();
    }

    /**
     * Create an instance of {@link CteObject }
     * 
     */
    public C /**
     * Create an instance of {@link Mark }
     * 
     */
    public Mark createMark() {
        return new Mark();
    }

    /**
     * Create an instance of {@link TestGroup.TestCase }
     /
    public TestGroup createTestGroup() {
        return new TestGroup();
    }

    /**
     * Create an instance of {@link Composition }
     * 
     */
    public CompMark.Tag.Content }
     * 
     */
    public Mark.Tag.Content createMarkTagContent() {
        return new Mark.Tag.Content();
    }

  * 
     */
    public TestGroup.TestCase createTestGroupTestCase() {
        return new TestGroup.TestCase();
    }

    /**
     * Create an instance of {@link Mark.Tag }
     * 
     */
    pubcreateComposition() {
        return new Composition();
    }

    /**
     * Create an instance of {@link Marks }
     * 
     */
    public Marks createMarks() {
      cation }
     * 
     */
    public Classification createClassification() {
        return new Classification();
    }

nstance of {@link Class }
     * 
     */
    public Class createClass() {
        return new Class();
    }

    /**
     * Create an instance of {@link TestGroup }
     * 
     */ /**
     * Create an instance of {@link CteObject.Tree }
     * 
     */
    public CteObject.Tree createCteObjectTree() {
        return new CteObject.Tree();
    }

   
    public Mark.Tag createMarkTag() {
        return new Mark.Tag();
    }

    /**
     * Create an i}
