//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 12:50:36 PM CET 
//


package eu.fittest.eventabstraction;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.fittest.eventabstraction package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Eventabstraction_QNAME = new QName("http://fittest.eu/eventabstraction", "eventabstraction");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.fittest.eventabstraction
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Regexp }
     * 
     */
    public Regexp createRegexp() {
        return new Regexp();
    }

    /**
     * Create an instance of {@link Path }
     * 
     */
    public Path createPath() {
        return new Path();
    }

    /**
     * Create an instance of {@link Abstraction }
     * 
     */
    public Abstraction createAbstraction() {
        return new Abstraction();
    }

    /**
     * Create an instance of {@link Abstractions }
     * 
     */
    public Abstractions createAbstractions() {
        return new Abstractions();
    }

    /**
     * Create an instance of {@link Rewrites }
     * 
     */
    public Rewrites createRewrites() {
        return new Rewrites();
    }

    /**
     * Create an instance of {@link Rule }
     * 
     */
    public Rule createRule() {
        return new Rule();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link EmptyNonempty }
     * 
     */
    public EmptyNonempty createEmptyNonempty() {
        return new EmptyNonempty();
    }

    /**
     * Create an instance of {@link Eventabstraction }
     * 
     */
    public Eventabstraction createEventabstraction() {
        return new Eventabstraction();
    }

    /**
     * Create an instance of {@link Abstractionspaths }
     * 
     */
    public Abstractionspaths createAbstractionspaths() {
        return new Abstractionspaths();
    }

    /**
     * Create an instance of {@link Ignore }
     * 
     */
    public Ignore createIgnore() {
        return new Ignore();
    }

    /**
     * Create an instance of {@link ZeroNonzero }
     * 
     */
    public ZeroNonzero createZeroNonzero() {
        return new ZeroNonzero();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Eventabstraction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fittest.eu/eventabstraction", name = "eventabstraction")
    public JAXBElement<Eventabstraction> createEventabstraction(Eventabstraction value) {
        return new JAXBElement<Eventabstraction>(_Eventabstraction_QNAME, Eventabstraction.class, null, value);
    }

}
