//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 12:50:28 PM CET 
//


package eu.fittest.common.core.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}Message">
 *       &lt;sequence>
 *         &lt;element name="allow-access-from">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="domain" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="to-ports" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "allowAccessFrom"
})
@XmlRootElement(name = "cross-domain-policy")
public class CrossDomainPolicy
    extends Message
{

    @XmlElement(name = "allow-access-from", required = true)
    protected CrossDomainPolicy.AllowAccessFrom allowAccessFrom;

    /**
     * Gets the value of the allowAccessFrom property.
     * 
     * @return
     *     possible object is
     *     {@link CrossDomainPolicy.AllowAccessFrom }
     *     
     */
    public CrossDomainPolicy.AllowAccessFrom getAllowAccessFrom() {
        return allowAccessFrom;
    }

    /**
     * Sets the value of the allowAccessFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrossDomainPolicy.AllowAccessFrom }
     *     
     */
    public void setAllowAccessFrom(CrossDomainPolicy.AllowAccessFrom value) {
        this.allowAccessFrom = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="domain" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="to-ports" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AllowAccessFrom {

        @XmlAttribute
        protected String domain;
        @XmlAttribute(name = "to-ports")
        protected String toPorts;

        /**
         * Gets the value of the domain property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDomain() {
            return domain;
        }

        /**
         * Sets the value of the domain property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDomain(String value) {
            this.domain = value;
        }

        /**
         * Gets the value of the toPorts property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getToPorts() {
            return toPorts;
        }

        /**
         * Sets the value of the toPorts property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setToPorts(String value) {
            this.toPorts = value;
        }

    }

}
