//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 12:50:28 PM CET 
//


package eu.fittest.common.core.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}Message">
 *       &lt;sequence>
 *         &lt;element name="fittestEntityName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="environment" type="{}HUTEnvironment"/>
 *         &lt;element name="type" type="{}HUTType"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fittestEntityName",
    "environment",
    "type",
    "description"
})
@XmlRootElement(name = "RegisterAgent")
public class RegisterAgent
    extends Message
{

    @XmlElement(required = true)
    protected String fittestEntityName;
    @XmlElement(required = true)
    protected HUTEnvironment environment;
    @XmlElement(required = true)
    protected HUTType type;
    @XmlElement(required = true)
    protected String description;

    /**
     * Gets the value of the fittestEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFittestEntityName() {
        return fittestEntityName;
    }

    /**
     * Sets the value of the fittestEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFittestEntityName(String value) {
        this.fittestEntityName = value;
    }

    /**
     * Gets the value of the environment property.
     * 
     * @return
     *     possible object is
     *     {@link HUTEnvironment }
     *     
     */
    public HUTEnvironment getEnvironment() {
        return environment;
    }

    /**
     * Sets the value of the environment property.
     * 
     * @param value
     *     allowed object is
     *     {@link HUTEnvironment }
     *     
     */
    public void setEnvironment(HUTEnvironment value) {
        this.environment = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link HUTType }
     *     
     */
    public HUTType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link HUTType }
     *     
     */
    public void setType(HUTType value) {
        this.type = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
