//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 12:50:28 PM CET 
//


package eu.fittest.common.core.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}Message">
 *       &lt;sequence>
 *         &lt;element name="fittestIteId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fittestAgentId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fittestLease" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="fittestComponentDir" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fittestComponentId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fittestIteId",
    "fittestAgentId",
    "fittestLease",
    "fittestComponentDir",
    "fittestComponentId"
})
@XmlRootElement(name = "RegisterResponse")
public class RegisterResponse
    extends Message
{

    @XmlElement(required = true)
    protected String fittestIteId;
    @XmlElement(required = true)
    protected String fittestAgentId;
    protected long fittestLease;
    protected String fittestComponentDir;
    protected String fittestComponentId;

    /**
     * Gets the value of the fittestIteId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFittestIteId() {
        return fittestIteId;
    }

    /**
     * Sets the value of the fittestIteId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFittestIteId(String value) {
        this.fittestIteId = value;
    }

    /**
     * Gets the value of the fittestAgentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFittestAgentId() {
        return fittestAgentId;
    }

    /**
     * Sets the value of the fittestAgentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFittestAgentId(String value) {
        this.fittestAgentId = value;
    }

    /**
     * Gets the value of the fittestLease property.
     * 
     */
    public long getFittestLease() {
        return fittestLease;
    }

    /**
     * Sets the value of the fittestLease property.
     * 
     */
    public void setFittestLease(long value) {
        this.fittestLease = value;
    }

    /**
     * Gets the value of the fittestComponentDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFittestComponentDir() {
        return fittestComponentDir;
    }

    /**
     * Sets the value of the fittestComponentDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFittestComponentDir(String value) {
        this.fittestComponentDir = value;
    }

    /**
     * Gets the value of the fittestComponentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFittestComponentId() {
        return fittestComponentId;
    }

    /**
     * Sets the value of the fittestComponentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFittestComponentId(String value) {
        this.fittestComponentId = value;
    }

}
