//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 12:51:31 PM CET 
//


package eu.fittest.project.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GAParameterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GAParameterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="populationSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="chromosomeLength" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maxNumberOfGenerations" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="mutationRate" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="timeBudget" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="stopPort" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GAParameterType", propOrder = {
    "populationSize",
    "chromosomeLength",
    "maxNumberOfGenerations",
    "mutationRate",
    "timeBudget",
    "stopPort"
})
public class GAParameterType {

    protected int populationSize;
    protected int chromosomeLength;
    protected int maxNumberOfGenerations;
    protected double mutationRate;
    protected int timeBudget;
    protected int stopPort;

    /**
     * Gets the value of the populationSize property.
     * 
     */
    public int getPopulationSize() {
        return populationSize;
    }

    /**
     * Sets the value of the populationSize property.
     * 
     */
    public void setPopulationSize(int value) {
        this.populationSize = value;
    }

    /**
     * Gets the value of the chromosomeLength property.
     * 
     */
    public int getChromosomeLength() {
        return chromosomeLength;
    }

    /**
     * Sets the value of the chromosomeLength property.
     * 
     */
    public void setChromosomeLength(int value) {
        this.chromosomeLength = value;
    }

    /**
     * Gets the value of the maxNumberOfGenerations property.
     * 
     */
    public int getMaxNumberOfGenerations() {
        return maxNumberOfGenerations;
    }

    /**
     * Sets the value of the maxNumberOfGenerations property.
     * 
     */
    public void setMaxNumberOfGenerations(int value) {
        this.maxNumberOfGenerations = value;
    }

    /**
     * Gets the value of the mutationRate property.
     * 
     */
    public double getMutationRate() {
        return mutationRate;
    }

    /**
     * Sets the value of the mutationRate property.
     * 
     */
    public void setMutationRate(double value) {
        this.mutationRate = value;
    }

    /**
     * Gets the value of the timeBudget property.
     * 
     */
    public int getTimeBudget() {
        return timeBudget;
    }

    /**
     * Sets the value of the timeBudget property.
     * 
     */
    public void setTimeBudget(int value) {
        this.timeBudget = value;
    }

    /**
     * Gets the value of the stopPort property.
     * 
     */
    public int getStopPort() {
        return stopPort;
    }

    /**
     * Sets the value of the stopPort property.
     * 
     */
    public void setStopPort(int value) {
        this.stopPort = value;
    }

}
