//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 12:51:31 PM CET 
//


package eu.fittest.project.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeneralType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeneralType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://www.fittest.eu/TestProject}SUTTechnologyType"/>
 *         &lt;element name="baseURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="entryPage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="serverFolder" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeneralType", propOrder = {
    "type",
    "baseURL",
    "entryPage",
    "serverFolder"
})
public class GeneralType {

    @XmlElement(required = true, defaultValue = "FLASH")
    protected SUTTechnologyType type;
    @XmlElement(required = true)
    protected String baseURL;
    @XmlElement(required = true)
    protected String entryPage;
    protected String serverFolder;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link SUTTechnologyType }
     *     
     */
    public SUTTechnologyType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link SUTTechnologyType }
     *     
     */
    public void setType(SUTTechnologyType value) {
        this.type = value;
    }

    /**
     * Gets the value of the baseURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseURL() {
        return baseURL;
    }

    /**
     * Sets the value of the baseURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseURL(String value) {
        this.baseURL = value;
    }

    /**
     * Gets the value of the entryPage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryPage() {
        return entryPage;
    }

    /**
     * Sets the value of the entryPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryPage(String value) {
        this.entryPage = value;
    }

    /**
     * Gets the value of the serverFolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerFolder() {
        return serverFolder;
    }

    /**
     * Sets the value of the serverFolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerFolder(String value) {
        this.serverFolder = value;
    }

}
