//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 12:51:31 PM CET 
//


package eu.fittest.project.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LogTargetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LogTargetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="storeDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="logLevel" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LogTargetType", propOrder = {
    "storeDir",
    "logLevel"
})
public class LogTargetType {

    @XmlElement(required = true)
    protected String storeDir;
    protected int logLevel;

    /**
     * Gets the value of the storeDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoreDir() {
        return storeDir;
    }

    /**
     * Sets the value of the storeDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoreDir(String value) {
        this.storeDir = value;
    }

    /**
     * Gets the value of the logLevel property.
     * 
     */
    public int getLogLevel() {
        return logLevel;
    }

    /**
     * Sets the value of the logLevel property.
     * 
     */
    public void setLogLevel(int value) {
        this.logLevel = value;
    }

}
