//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 12:51:31 PM CET 
//


package eu.fittest.project.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestGenerationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestGenerationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cteFolder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modelVisitStrategy" type="{http://www.fittest.eu/TestProject}ModelVisitStrategyType"/>
 *         &lt;element name="reduceTestSuite" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="sourcePackagePrefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="seleniumDriverBrowser" type="{http://www.fittest.eu/TestProject}BrowserType"/>
 *         &lt;element name="seleniumRemoteHost" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="seleniumRemotePort" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="seleniumBrowserConfig" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gaParam" type="{http://www.fittest.eu/TestProject}GAParameterType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestGenerationType", propOrder = {
    "cteFolder",
    "modelVisitStrategy",
    "reduceTestSuite",
    "sourcePackagePrefix",
    "seleniumDriverBrowser",
    "seleniumRemoteHost",
    "seleniumRemotePort",
    "seleniumBrowserConfig",
    "gaParam"
})
public class TestGenerationType {

    @XmlElement(required = true)
    protected String cteFolder;
    @XmlElement(required = true)
    protected ModelVisitStrategyType modelVisitStrategy;
    protected boolean reduceTestSuite;
    @XmlElement(required = true)
    protected String sourcePackagePrefix;
    @XmlElement(required = true)
    protected BrowserType seleniumDriverBrowser;
    @XmlElement(required = true)
    protected String seleniumRemoteHost;
    protected int seleniumRemotePort;
    @XmlElement(required = true)
    protected String seleniumBrowserConfig;
    @XmlElement(required = true)
    protected GAParameterType gaParam;

    /**
     * Gets the value of the cteFolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCteFolder() {
        return cteFolder;
    }

    /**
     * Sets the value of the cteFolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCteFolder(String value) {
        this.cteFolder = value;
    }

    /**
     * Gets the value of the modelVisitStrategy property.
     * 
     * @return
     *     possible object is
     *     {@link ModelVisitStrategyType }
     *     
     */
    public ModelVisitStrategyType getModelVisitStrategy() {
        return modelVisitStrategy;
    }

    /**
     * Sets the value of the modelVisitStrategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelVisitStrategyType }
     *     
     */
    public void setModelVisitStrategy(ModelVisitStrategyType value) {
        this.modelVisitStrategy = value;
    }

    /**
     * Gets the value of the reduceTestSuite property.
     * 
     */
    public boolean isReduceTestSuite() {
        return reduceTestSuite;
    }

    /**
     * Sets the value of the reduceTestSuite property.
     * 
     */
    public void setReduceTestSuite(boolean value) {
        this.reduceTestSuite = value;
    }

    /**
     * Gets the value of the sourcePackagePrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcePackagePrefix() {
        return sourcePackagePrefix;
    }

    /**
     * Sets the value of the sourcePackagePrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcePackagePrefix(String value) {
        this.sourcePackagePrefix = value;
    }

    /**
     * Gets the value of the seleniumDriverBrowser property.
     * 
     * @return
     *     possible object is
     *     {@link BrowserType }
     *     
     */
    public BrowserType getSeleniumDriverBrowser() {
        return seleniumDriverBrowser;
    }

    /**
     * Sets the value of the seleniumDriverBrowser property.
     * 
     * @param value
     *     allowed object is
     *     {@link BrowserType }
     *     
     */
    public void setSeleniumDriverBrowser(BrowserType value) {
        this.seleniumDriverBrowser = value;
    }

    /**
     * Gets the value of the seleniumRemoteHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeleniumRemoteHost() {
        return seleniumRemoteHost;
    }

    /**
     * Sets the value of the seleniumRemoteHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeleniumRemoteHost(String value) {
        this.seleniumRemoteHost = value;
    }

    /**
     * Gets the value of the seleniumRemotePort property.
     * 
     */
    public int getSeleniumRemotePort() {
        return seleniumRemotePort;
    }

    /**
     * Sets the value of the seleniumRemotePort property.
     * 
     */
    public void setSeleniumRemotePort(int value) {
        this.seleniumRemotePort = value;
    }

    /**
     * Gets the value of the seleniumBrowserConfig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeleniumBrowserConfig() {
        return seleniumBrowserConfig;
    }

    /**
     * Sets the value of the seleniumBrowserConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeleniumBrowserConfig(String value) {
        this.seleniumBrowserConfig = value;
    }

    /**
     * Gets the value of the gaParam property.
     * 
     * @return
     *     possible object is
     *     {@link GAParameterType }
     *     
     */
    public GAParameterType getGaParam() {
        return gaParam;
    }

    /**
     * Sets the value of the gaParam property.
     * 
     * @param value
     *     allowed object is
     *     {@link GAParameterType }
     *     
     */
    public void setGaParam(GAParameterType value) {
        this.gaParam = value;
    }

}
