//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 12:51:31 PM CET 
//


package eu.fittest.project.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="General" type="{http://www.fittest.eu/TestProject}GeneralType"/>
 *         &lt;element name="Logging" type="{http://www.fittest.eu/TestProject}LoggingType"/>
 *         &lt;element name="ModelInference" type="{http://www.fittest.eu/TestProject}ModelInferenceType"/>
 *         &lt;element name="TestGeneration" type="{http://www.fittest.eu/TestProject}TestGenerationType"/>
 *         &lt;element name="Oracle" type="{http://www.fittest.eu/TestProject}OracleType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "general",
    "logging",
    "modelInference",
    "testGeneration",
    "oracle"
})
@XmlRootElement(name = "TestProject")
public class TestProject {

    @XmlElement(name = "General", required = true)
    protected GeneralType general;
    @XmlElement(name = "Logging", required = true)
    protected LoggingType logging;
    @XmlElement(name = "ModelInference", required = true)
    protected ModelInferenceType modelInference;
    @XmlElement(name = "TestGeneration", required = true)
    protected TestGenerationType testGeneration;
    @XmlElement(name = "Oracle", required = true)
    protected OracleType oracle;

    /**
     * Gets the value of the general property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralType }
     *     
     */
    public GeneralType getGeneral() {
        return general;
    }

    /**
     * Sets the value of the general property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralType }
     *     
     */
    public void setGeneral(GeneralType value) {
        this.general = value;
    }

    /**
     * Gets the value of the logging property.
     * 
     * @return
     *     possible object is
     *     {@link LoggingType }
     *     
     */
    public LoggingType getLogging() {
        return logging;
    }

    /**
     * Sets the value of the logging property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoggingType }
     *     
     */
    public void setLogging(LoggingType value) {
        this.logging = value;
    }

    /**
     * Gets the value of the modelInference property.
     * 
     * @return
     *     possible object is
     *     {@link ModelInferenceType }
     *     
     */
    public ModelInferenceType getModelInference() {
        return modelInference;
    }

    /**
     * Sets the value of the modelInference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelInferenceType }
     *     
     */
    public void setModelInference(ModelInferenceType value) {
        this.modelInference = value;
    }

    /**
     * Gets the value of the testGeneration property.
     * 
     * @return
     *     possible object is
     *     {@link TestGenerationType }
     *     
     */
    public TestGenerationType getTestGeneration() {
        return testGeneration;
    }

    /**
     * Sets the value of the testGeneration property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestGenerationType }
     *     
     */
    public void setTestGeneration(TestGenerationType value) {
        this.testGeneration = value;
    }

    /**
     * Gets the value of the oracle property.
     * 
     * @return
     *     possible object is
     *     {@link OracleType }
     *     
     */
    public OracleType getOracle() {
        return oracle;
    }

    /**
     * Sets the value of the oracle property.
     * 
     * @param value
     *     allowed object is
     *     {@link OracleType }
     *     
     */
    public void setOracle(OracleType value) {
        this.oracle = value;
    }

}
