//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.13 at 04:11:15 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.fbk.eu/xinput", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.fbk.se.fsm.xinput;
