//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.23 at 01:35:30 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/1999/xhtml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.w3c.xhtml1;
